### PR TITLE
fix(rest): error when stopping an app that hasn't been started

### LINKED ISSUE #822: Error when stopping an App that hasn't been started
## Description/Steps to reproduce

While writing some tests, the cleanup code always runs `await app.stop()`. However if the app wasn't started, trying to stop the app throws the following error message.

```
TypeError: Cannot read property 'close' of undefined
    at Promise (/Users/taranveer/loopback/loopback-next/random/node_modules/@loopback/rest/dist/src/rest-server.js:417:20)
    at new Promise (<anonymous>)
    at RestServer.stop (/Users/taranveer/loopback/loopback-next/random/node_modules/@loopback/rest/dist/src/rest-server.js:416:16)
    at _forEachServer.s (/Users/taranveer/loopback/loopback-next/random/node_modules/@loopback/core/dist/src/application.js:134:42)
    at Promise.all.bindings.map (/Users/taranveer/loopback/loopback-next/random/node_modules/@loopback/core/dist/src/application.js:148:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Is this expected behaviour? Should stop catch error messages which indicate the server was never running and hence the app was successfully stopped?

## Link to reproduction sandbox

Create app using `lb4 app`. 
Create a new instance `const app = new Application()` ... now run `app.stop()` before starting it. 

## Expected result
Is this the designed behaviour? I think it might be more intuitive to not thrown an error if a server is already stopped. Stop should throw a error is it wasn't able to stop a server. 

## Acceptance Criteria
- [ ] `@loopback/rest/src/rest-server.ts` has a `stop` method -- It shouldn't throw an error if a server can't be stopped if it was never started! -- Other error's should still be propagated.
- [ ] Test coverage for this scenario

### PR DESCRIPTION
**Pull request by m3hari**
Fixes #822

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by raymondfeng** [comment]
@m3hari Did you close this PR intentionally?

**Comment by m3hari** [comment]
Yes, I have noticed the coverage decreases,hence I want to fix it. how can I run the coverage tool locally?

**Comment by virkt25** [comment]
The decrease in coverage was minimal and due to the new test case itself ... so I think it can be ignored OR the test can be rewritten so you expect the error to be thrown instead of catching it. 

You can view the report here: https://coveralls.io/builds/17449934
You can run coverage locally by running `npm run coverage` from the repository root.

**Comment by m3hari** [comment]
Thanks @virKt25 I improved the coverage and open new PR

**Comment by m3hari** [comment]
@bajtos Thanks! Will do.

**Pull request closed without merging**
