### PR TITLE
Fix the file names and debug info to use lower cases

### PR DESCRIPTION
**Pull request by raymondfeng**
cc @bajtos @raymondfeng @ritch @superkhau

### CODE REVIEW

**Comment by bajtos** [comment]
> Fix the file names to use lower cases

A mild -1 from me.

I wanted to write that the TypeScript convention is to use the same file name as is the main exported class, e.g. `SwaggerRouter` class is defined in file `SwaggerRouter.ts`, but when I searched google for [typescript file name convention](https://www.google.com/search?q=typescript+file+name+convention), I did not find any strong argument to support that claim.

Looks like we have to make up our own convention.

**Comment by raymondfeng** [comment]
@bajtos Some file systems such as Mac or Windows are case insensitive. Consistently have lower case file names make our life easier.

**Comment by raymondfeng** [comment]
@bajtos PTAL

**Comment by bajtos** [comment]
I'd like to get input from more people before making the decision here.

@ritch @superkhau @strongloop/loopback-next 

We are debating what convention to use for file names.

  - I am proposing to use the same file name as is the exported class, e.g. `class SwaggerRouter` goes to `SwaggerRouter.ts`.

 - Raymond is proposing to use [param-case](https://github.com/blakeembrey/param-case) where `class SwaggerRouter` goes to `swagger-router.ts`.

I did a bit of research and did not found any guidance on what is the recommended file naming convention in TypeScript, in which case it's up to us to decide what convention we want to use.

I think each style has its pros and cons, here is my understanding so far:

**param-case**

Pros:
 - We are already using this convention in the current LoopBack (3.x) codebase.
 - Makes more sense when a file exports more than a single type (e.g. `router.ts` can export `class SwaggerRouter`, `class Endpoint`, `interface HttpError`, etc.).

Cons:
 - It's not immediately clear what filename to use, should `SwaggerRouter` live in `router.ts` or `swagger-router.ts`?

**PascalCase**

Pros:

 - Familiar to people coming from Java/C# background.
 - The filename is clear for files exporting a class.

Cons:

 - What name to use when a file exports more than a single class and/or a bunch of functions?
 - The style is different from what most of existing Node.js modules use.

What are the other pros and cons to add to this list? Are there any deal-breakers?

Please exclude points that are too subjective and keep the discussion civilised, I don't want to start any flamewars.

**Comment by shairez** [comment]
I think that the single vs many exports argument isn't strongly coupled to the file naming convention.

Because as you said, you could still have `components.ts` which could export a single component, or `Router.ts` which exports a bunch of things. 

I think by choosing more meaningful names for multi exporting stuff (like `routing-module.ts` instead of `router`), we could solve the issue of conveying the intent.

For me -  👍 for param-case or "kebab-case" 

Only because I'm already used to it when writing Node or Client side javascript.

So if our generated files will also be CamelCase, users projects could end up having a mix of two conventions in the same project which wouldn't look so nice IMO.

`package.json`
`MyModel.ts`
`my-other-node-file.js`
`...`

**Comment by bajtos** [comment]
@raymondfeng I am proposing to allow few more days for people to comment on, I'd especially like to hear from @superkhau when he gets back next week. If we don't find any compelling arguments for PascalCase or against kebab-case by then, then I am fine with going forward with this change.

Having said that, I'd like to see the final convention documented. Perhaps we should start `docs/coding-style-guide.md` to capture conventions that are different from/additional to http://loopback.io/doc/en/contrib/style-guide.html. That way the pull request changing file names can (and should) include an accompanying entry in the coding-style guide.

Thoughts?

**Comment by kjdelisle** [comment]
I thought the primary purpose of "kebab case" was maximum compatibility with all OSes?

If that's a non-concern, then my vote is definitely to match module names to their file names as PascalCase.

**Comment by raymondfeng** [comment]
@kjdelisle Yes. I propose to use `kebab case` to avoid casing confusions across different OSes. 

A few more references:

1. https://www.w3schools.com/js/js_conventions.asp (Always use lower-case file names)
2. https://angular.io/styleguide#!#naming

**Comment by bajtos** [comment]
> https://angular.io/styleguide#!#naming

That's a good reference indeed 👍

**Comment by superkhau** [comment]
+1 for kebab-case for case sensitivity concerns between OSes.

That said, I'm also +1 for starting our coding style guide to document the decisions we made and why (similar to the Angular reference with our touches). I'm also -1 for docs dir, let's use wiki instead to prevent tons of useless editing PRs -- reference for this PR started at https://github.com/strongloop/loopback-next/wiki/Coding-style-guide.

**Comment by bajtos** [comment]
Thank you all for your comments. As I was thinking about the naming convention in the last few days, I have reached the same conclusion that we should move to kebab case.

@raymondfeng could you please rebase your patch on top of master so that we can move forward and get it landed?

**Pull request merged**
