### PR TITLE
style: use lambda function to reset sandbox

### PR DESCRIPTION
**Pull request by virkt25**
I'm using this style for the repository booter #1030 and think it's cleaner and makes code easier to read and understand as the `resetSandbox` function was just one line. Didn't want to add this to the same PR since it's unrelated files so making a new PR to keep style consistent. 

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] Related API Documentation was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

**Comment by virkt25** [comment]
That is what I initially had but a comment (https://github.com/strongloop/loopback-next/pull/1030#discussion_r170044857) by @jannyHou made me reconsider (Note: Comment is collapsed so you'll have to click). The `beforeEach` hook is calling the lambda function which itself is not returning a promise, it's calling `sandbox.reset()` and exits. 

My validation came from the `example-getting-started` package where I removed `async` and `await` calls from the lambda function in the `before` hook (acceptance test) and the test failed because `boot` hadn't completed but the `givenTodoRepository` function was called. 

Am I missing something?

**Comment by raymondfeng** [comment]
If Mocha's `beforeEach()` receives a function that returns a promise, it will wait for the promise to be resolved or rejected. `beforeEach(() => sandbox.reset());` is similar as `beforeEach(function() { return sandbox.reset(); })`. As long as `sandbox.reset()` returns a promise, it should work as expected.

**Comment by jannyHou** [comment]
@virkt25 I think Raymond is right, sorry my comment misguide you :(

```ts
let count = 0;
class Test {
  async foo() {
    let promise1 = new Promise(function(resolve, reject) {
      setTimeout(function() {count = 1500; resolve(count)}, 1500);
    });
    return promise1;
  }
}
let inst: Test = new Test();
describe('test async', () => {
  beforeEach('async each', () => inst.foo());
  it('test', () => {
    console.log(count);
    // it prints out 1500
  })
})
```

**Comment by virkt25** [comment]
Good point @raymondfeng, forgot arrow functions have an implicit return. Updated the PR.

**Comment by bajtos** [comment]
+1, I like your proposed style too.

There are some caveats though, see http://loopback.io/doc/en/contrib/style-guide.html#hooks

> When writing hooks like before and after, it’s important to prepare for the situation when the hook fails and make troubleshooting easy in such case. There are two considerations to keep in mind:
>
> - What is printed by Mocha in the test output. When a test fails, Mocha prints the test name. When a hook fails, Mocha prints the hook name, but only if there was one provided!
>
> - What is reported by Node.js/V8 runtime in the stack trace.

I think the following would address those concerns?

```ts
beforeEach('reset sandbox', () => sandbox.reset());
```

**Comment by bajtos** [comment]
Another options is to modify the Sandbox class to provide a member that has `this` bound to the sandbox instance, so that one can write:

```ts
beforeEach(sandbox.reset);
```

This can be accomplished e.g. as follows:

```ts
export class TestSandbox  {
  reset: () => Promise<void>;

  constructor() {
    // ...
    this.reset = () => this._reset();
  }

  // renamed from public "reset" to private "_reset"
  private async _reset(): Promise<void> {
    // ...
  }
}
```

**Comment by raymondfeng** [comment]
@virkt25 Are you still interested in moving forward with this PR?

**Pull request merged**
