### PR TITLE
docs: Fix wording

### PR DESCRIPTION
**Pull request by mhdawson**
Fix awkward wording in Controllers.md

## Checklist

- [X] `npm test` passes on your machine
- [X] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [X] Documentation in [/docs/site](../tree/master/docs/site) was updated

### CODE REVIEW

**Comment by marioestradarosa** [comment]
👍 nice catch @mhdawson !

Please sign CLA at https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by dhmlau** [comment]
@rmg, I think you've mentioned before that how we can set up so that IBMers don't need to sign, but I forgot exactly how.

**Comment by mhdawson** [comment]
Have already signed the CLA

**Comment by mhdawson** [comment]
@raymondfeng done.

**Comment by dhmlau** [comment]
Thanks @mhdawson for your contribution.  Your PR has landed. 🎉

**Pull request merged**
