### PR TITLE
fix(docs): grammar fix on todo-tutorial-datasource.md

### PR DESCRIPTION
**Pull request by frey1esm**
Just a grammar fix in the tutorial.

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated
- [ x] Agree to the CLA (Contributor License Agreement) by [clicking and signing](https://cla.strongloop.com/agreements/strongloop/loopback-next)

### CODE REVIEW

**Comment by dhmlau** [comment]
@frey1esm , thanks for the PR.  Could you please sign the CLA?  https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by frey1esm** [comment]
> @frey1esm , thanks for the PR. Could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-next

Unfortunately it's hanging then throwing a 500.

**Comment by dhmlau** [comment]
@frey1esm, now it shows that you've signed. 
There's a linting error about the commit message. I'd suggest changing the commit message to be something like:
```
fix(docs): grammar fix on todo-tutorial-datasource.md
```

Just in case, you can change the commit message by `git commit --amend` command.  See instructions: https://help.github.com/articles/changing-a-commit-message/

Please see our commit message guideline: https://loopback.io/doc/en/contrib/code-contrib-lb4.html#commit-message-guidelines.

**Comment by frey1esm** [comment]
@dhmlau  I pulled my forked repo down and changed to 'patch-1' branch. But my commit isn't  listed at all in `git log`.   `git commit --amend` pulls up the most recent commit from `master` even though I checked out `patch-1`.

**Comment by raymondfeng** [comment]
@frey1esm You need to run `git rebase upstream/master` instead of git merge.

**Comment by dhmlau** [comment]
@slnode test please

**Pull request merged**
