### PR TITLE
fix(docs): upgrade to strong-docs@3.1.0 and fix links

### LINKED ISSUE #1413: apidocs links are broken and anchors are non-descriptive
## Description / Steps to reproduce / Feature proposal

After we moved loopback4 apidocs main page to this repo, the base link for it has been changed which invalidates our existing apidocs links in the docs.

Additionally, some of the links with anchors to them are non-descriptive and seem easily subject to change (e.g. link to apidocs for Context's `get` is  http://apidocs.loopback.io/@loopback%2fdocs/context.html#216; the anchor is not #get). We should either address this directly by adjusting strong-docs, or have a standard procedure for linking to code/apidocs so that they're not prone to breaking.

## Acceptance Criteria
- fix all broken apidocs links
- follow up with **an issue** for making the anchor generation more maintainable

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by raymondfeng**
Fixes #1413

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by shimks** [comment]
The links are still broken :/

**Comment by raymondfeng** [comment]
> The links are still broken :/

Which ones? How did you verify?

**Comment by shimks** [comment]
The pattern to the http path to apidocs is something like this: http://apidocs.loopback.io/@loopback%2fdocs/repository.html
We have `@loopback/docs` followed by the package name `repository` in this case.
The docs were broken because it wasn't updated after the refactor of apidocs when we moved them to be built in `@loopback/docs`.

**Comment by raymondfeng** [comment]
@shimks Good catch. They are now fixed. PTAL.

**Comment by shimks** [comment]
Could you also update `Application.md`, `Context.md`, `Sequence.md`, `Server.md` and `todo-tutorial-scaffolding.md`?

**Comment by raymondfeng** [comment]
@shimks PTAL

**Pull request merged**
