### PR TITLE
fix(repository-json-schema): fix schema generation for model inheritance

### PR DESCRIPTION
**Pull request by raymondfeng**
Fixes https://github.com/strongloop/loopback-next/issues/4721

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dougal83** [comment]
I've run against example in the sandbox and it gives `422: Error: Unprocessable Entity`.  Definitely a step in the right direction as the password is now present in the request body.

```json
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `User` instance is not valid. Details: `password` is not defined in the model (value: undefined).",
    "details": {
      "context": "User",
      "codes": {
        "password": [
          "unknown-property"
        ]
      },
      "messages": {
        "password": [
          "is not defined in the model"
        ]
      }
    }
  }
}
```

Happy to do further testing against the example app in ref. issue.

**Comment by raymondfeng** [comment]
Did you rebuild repository package?

**Comment by emonddr** [comment]
@dougal83 , you need to remove the password before you return the User. User does not allow `password`. See my latest comments today.

**Comment by emonddr** [comment]
```
 async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(NewUserRequest, {
            title: 'NewUser',
            exclude: ['id'],
          }),
        },
      },
    })
    user: Omit<NewUserRequest, 'id'>,
  ): Promise<User> {
    const createdUserWithoutPassword = await this.userRepository.create(
      _.omit(user, 'password'),
    );
    return createdUserWithoutPassword;
  }
```

**Comment by emonddr** [comment]
I mentioned this in : https://github.com/strongloop/loopback-next/issues/4721#issuecomment-603275546

**Comment by raymondfeng** [comment]
@dougal83 I debugged your app. The request validation at REST layer is now passing. But the controller and repository have further issues in your app:

1. The UserRepository expects a `User` and it reports validation errors at juggler bridge due to the unknown `password`
2. See the controller code:

````ts
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(NewUserRequest, {
            title: 'NewUser',
            exclude: ['id'],
          }),
        },
      },
    })
    user: Omit<NewUserRequest, 'id'>,
  ): Promise<User> {
   // The user repo does not accept new user request with password
   // The following line throws validation error
    const created = await this.userRepository.create(user) as NewUserRequest;
   // we need to delete the password for the response too
    delete created.password;
    return created;
  }
```

**Comment by emonddr** [comment]
@raymondfeng , yes as per my comment above.

**Comment by emonddr** [comment]
image

**Comment by emonddr** [comment]
image

**Pull request merged**
