### PR TITLE
Todolist example 6733

### PR DESCRIPTION
**Pull request by norricorp**
Fix for #6733. In summary, model uses "color" but db.json used "dateModified".

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@norricorp, thanks for the PR. It seems like your PR includes other commits. Could you please try:
```
git fetch origin
git rebase origin/master
```

Thanks @nabdelgadir for providing the steps in PR https://github.com/strongloop/loopback-next/issues/6809.

**Comment by norricorp** [comment]
Perhaps it would be better if I started again.
Having kept my fork upto date on master (which struck me as the right thing to do) after my I made the changes on the issue branch, I merged master into the issue branch to make sure that the branch was conflict free. 
Which is presumably not the right thing to do.
So I can 

- delete my fork on github 
- delete local copy
- make new fork on git and clone locally
- make changes on branch
- do not merge master on to merge to keep up to date
- create new PR
Is this the best approach?

**Comment by dhmlau** [comment]
Seems to be fixed. :). I did the following:
```
git clone ${forked repository url}
cd ${repo}
git checkout ${branch user used to open PR}
git remote add upstream ${strongloop repo url}
git remote -v // optional - used to verify remotes you have setup
git fetch upstream
git rebase -i upstream/master 
git push origin +${branch you are on -- the one user used to open PR}
```

**Comment by dhmlau** [comment]
@norricorp, I've fixed your commit message to adhere our [commit message guideline](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines) and your sign off message from `John Norris` to `norricorp` as it's complained by the DCO bot. Hope it helps.

**Comment by norricorp** [comment]
So I should use my GitHub username rather than my real name.
"Interesting" aside, when Rational Team Concert did an integration with git, they coded it so that it broke if the name had so spaces ie real name.
Glad to see it works, look forward to seeing the updated doc pages

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
> So I should use my GitHub username rather than my real name.
> "Interesting" aside, when Rational Team Concert did an integration with git, they coded it so that it broke if the name had so spaces ie real name.

@nabdelgadir pointed out from the DCO-bot it's expecting the github id instead of the full name. I'm not familiar with RTC with git integration, I usually just use git command. :)

**Review by nabdelgadir — APPROVED** [review]

**Pull request merged**
