### PR TITLE
Implement hasAndBelongsToMany relation

### LINKED ISSUE #2043: Many to many relation (hasAndBelongsToMany)
## Description / Steps to reproduce / Feature proposal
I want to implement many to many relation in loopback4 but I couldn't see the article or any documentation regarding many to many relation

### LINKED ISSUE #2308: [Model Relation] hasAndBelongsToMany
## Description / Steps to reproduce / Feature proposal
Originated from https://github.com/strongloop/loopback-next/issues/2043

This issue is created specific for `hasAndBelongsToMany` because the original issue contains other types of model relation. 

A few comments from #2043 that are related to `hasAndBelongsToMany`.
- @bajtos gave some info and starting point on creating a new relation type: https://github.com/strongloop/loopback-next/issues/2043#issuecomment-441176508
- @RaphaelDrai posted a design doc on `hasAndBelongsToMany`: https://github.com/strongloop/loopback-next/issues/2043#issuecomment-447065436
   - I believe @bajtos suggested to make the design docs in `.md` or in gist for easier review (?)

cc @RaphaelDrai @TomerSalton @codejamninja  - because you've expressed interests to implement this mdoel relation type.  Please let me know if there's anything I can help facilitating.

### PR DESCRIPTION
**Pull request by frbuceta**
I have been testing relationships for a while and have decided to take the step of creating a draft. So you can advise me.

### Problems to solve:
- [ ] Delete `through entities` when `target entities` are deleted
- [ ] Build through repository inside

closes #2308
closes #2043 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by agnes512** [comment]
@frbuceta Hey! Thanks for starting on this 😄 I happen to work on HasManyThrough helpers & tests https://github.com/strongloop/loopback-next/pull/5354. I think these two relations have a lot in common. It'd be good to check out to prevent duplication. 

Also it's better to keep the scope of the PR small to make it easier for review, thanks!

**Comment by frbuceta** [comment]
> @frbuceta Hey! Thanks for starting on this 😄 I happen to work on HasManyThrough helpers & tests #5354. I think these two relations have a lot in common. It'd be good to check out to prevent duplication.
> 
> Also it's better to keep the scope of the PR small to make it easier for review, thanks!

I understand that the hasManyThrough relationship has data and the hasAndBelongsToMany does not

**Comment by bajtos** [comment]
IIRC, in LoopBack 3, `hasAndBelongsToMany` relation is implemented as a special case of `hasManyThrough` relation, where the API for setting up `hasAndBelongsToMany` relation only defines a new `through` model and delegates all work to `hasManyThrough` implementation. I think we should follow the same design in LoopBack 4 too, unless there are compelling reasons why that would be a bad idea?

/cc @raymondfeng

**Comment by frbuceta** [comment]
> IIRC, in LoopBack 3, `hasAndBelongsToMany` relation is implemented as a special case of `hasManyThrough` relation, where the API for setting up `hasAndBelongsToMany` relation only defines a new `through` model and delegates all work to `hasManyThrough` implementation. I think we should follow the same design in LoopBack 4 too, unless there are compelling reasons why that would be a bad idea?
> 
> /cc @raymondfeng

Then, I close the PR and when the HasManyThrough is implemented I look at how to do If nobody does it before

**Pull request closed without merging**
