### PR TITLE
[doc] Add `--port=3001` as documented

### PR DESCRIPTION
**Pull request by ceefour**
Without this, failed with address (port 3000) already in use

## Checklist

Error signing CLA: 👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

image

- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated

## Additional

Should add `--cors` as well?

### CODE REVIEW

**Comment by dhmlau** [comment]
@ceefour, thanks for catching this. Your changes LGTM, just need to fix the commit message. 

```
Without this, failed with address (port 3000) already in use
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
```

I'd suggest to prefix your commit message with `fix(docs)`.   See our commit message guideline for reference: https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines.

**Comment by raymondfeng** [comment]
@ceefour I have fixed the commit message for you.

**Comment by raymondfeng** [comment]
@ceefour PR landed. Thanks!

**Comment by ceefour** [comment]
Thank you @raymondfeng 

BTW I still am unable to sign the CLA (and most likely, everyone else)

image

**Pull request merged**
