### PR TITLE
refactor: remove hand-written index files 

### LINKED ISSUE #2609: Enable TypeScript Project References
At the moment, our monorepo is configured in a hacky way to allow TypeScript to build individual packages independently but still allow the TypeScript Language Service run by VSCode to treat the monorepo as one large project.

Let's abandon our non-standard setup and leverage TypeScript's [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) instead.

Work done so far:
- [x] build: drop multiple dist targets, always use es2017 #1803
- [x] refactor: let TypeScript do resource copying #1824
- [x] move test files to `src/__tests__` #2283 #2316 #2330 #2339

Work remaining:

- [ ] 🚶  remove top-level `index.*` files and use `main` & `types` entries in `package.json` instead #5440 ~~#2613~~ 
- [x]  chore: add script to build typescript project references #5155 ~~#1636~~
- [x] 🚶update example projects and CLI templates (if needed) #5204

Nice to have ~~implement it or create follow-up stories:~~
- Watch mode
- [x] Incremental builds - already done by #2928
- Incremental builds on Travis CI and AppVeyor - cache intermediate files between CI runs
  - Travis CI docs: https://docs.travis-ci.com/user/caching/
  - AppVeyor docs: https://www.appveyor.com/docs/build-cache/

### PR DESCRIPTION
**Pull request by bajtos**
1. The first commit moves `if (require.main === module)` code from `/index.js` to `src/index.ts`. This is a preparation to allow us to remove `/index.js` file entirely. It leaves the repository in a broken state, but that's fine because the next commit fixes the problem and will be squashed into this one before landing.

   This change has a nice benefit that it enables TypeScript compiler checks for the code building app config, it discovered a possible problem in `+process.env.PORT` line (`+undefined` returns `NaN`).

   I am also slightly changing exports to improve ergonomics - the type `ApplicationOptions` is exported together with the main application class, so that consumers don't need to import the options from `@loopback/context`.

2. In the next step, I am committing the outcome of running an automated script (see https://gist.github.com/bajtos/68672a8229bd03fddad5a4ad1442061f) to remove top-level index files and update `package.json` metadata.

3. In the third commit I am updating project templates in `packages/cli` to match the new style.

4. Finally I am updating documentation, tutorials and README files in `example/*`.

Resolves #2613, resolves  #2609

## Verification

Here are the steps I performed to verify that this change does not break our source-code editing experience in VS Code:

1. Run `npm run clean` to remove all `dist` folders 
2. Verify that VSCode is still able to understand relations between source code artifacts defined in one package (e.g. `context`) and used elsewhere (e.g. `example-todo`), as described in https://github.com/strongloop/loopback-next/blob/master/docs/site/VSCODE.md:

    > - Verify that "Go to definition" works across package boundaries. Find a place
where we are calling `@inject` in `authentication` package, press F12 to go to
the definition of `inject`. VSCode should jump to the `.ts` file in `src` (as
opposed to jumping to a `.d.ts` file in `dist`)
    > - Verify that refactorings like "rename symbol" (`F2`) will change all places
using the renamed entity. Two different scenarios to verify: rename at the place
where the entity is defined, rename at the place where the entity is used. (You
can e.g. rename `inject` to test.)

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@bajtos Please investigate why CI is failing.

**Comment by bajtos** [comment]
> To be done: update documentation, tutorials and README files in `example/*`.

Done in 834d6cdd3. I searched for all occurrences of the string `index.js` in `*.md` files to locate places needed an update.

**Comment by bajtos** [comment]
> Please investigate why CI is failing.

These failures are weird, I am not able to reproduce them in my working copy. I had to follow up the exact steps performed by Travis CI (starting from `git init` and `git remote add`) to get the build to fail locally (albeit with a slightly different message from Prettier).

2e32364 is fixing the problem.

Strangely enough, after fixing Mocha failures, I see linting errors now, in code that seem to be unrelated to my changes 😠

**Comment by bajtos** [comment]
Possibly related: https://github.com/typescript-eslint/typescript-eslint/issues/1573

**Comment by bajtos** [comment]
> Strangely enough, after fixing Mocha failures, I see linting errors now, in code that seem to be unrelated to my changes

I think this problem is caused by our `code-lint` script that runs `eslint` on the bare repository (without running `tsc` to build `dist` files first).

**Comment by bajtos** [comment]
I tried to configure `eslint` to be aware of TypeScript Project References (see 07b499e4), but that did not solve the problem :(

See also https://github.com/typescript-eslint/typescript-eslint/blob/795fd1c529ee58e97283c9ddf8463703517b50ab/packages/parser/README.md#parseroptionsproject

**Comment by bajtos** [comment]
@raymondfeng I added three new commits, PTAL:

- 834d6cdd update docs 
- 2e32364f2 fix yarn test failing on prettier
- b88c3d9 compile the code before running eslint on Travis CI 

I am not very happy about b88c3d9, but then it's affecting only one of the parallel jobs on CI, so it shouldn't make things any worse. 

I have some ideas how to improve our eslint setup so that the build step is hopefully not needed, but I prefer to leave them out of scope of this pull request and explore them after this PR is landed.

**Comment by bajtos** [comment]
> coverage/coveralls — Coverage decreased (-0.5%) to 91.666%

This is caused by the fact that our tests are not executing `main` functions in `src/index.ts`. I am surprised they were not detected by nyc/coveralls before my change, while the code was living in `index.js` files 🤷‍♂️

Screen Shot 2020-05-18 at 13 14 23

**Pull request merged**
