### PR TITLE
docs(cli): use a custom repository base class

### LINKED ISSUE #2149: [CLI] Use a custom Repository base class
Application developers invoking `lb4 repository` should be able to specify a custom Repository class to inherit from. This repository can be defined in a 3rd-party extension or inside the application project.

At minimum, the CLI should accept custom class name (+ import path?):
 - via an interactive prompt
 - via CLI options
 - via JSON config

Even better, there should be a mechanism allowing extensions (npm packages) and applications to define custom Repository implementations in such way that `lb4 repository` can pick them and create a list of available repositories for the CLI user to pick from.

See also https://github.com/strongloop/loopback-next/issues/2095#issuecomment-446182948

### PR DESCRIPTION
**Pull request by gczobel-f5**
fix #2149

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by gczobel-f5** [comment]
@bajtos @raymondfeng This is the documentation for https://github.com/strongloop/loopback-next/pull/2235

**Comment by nabdelgadir** [comment]
@gczobel-f5 thanks for the contribution! Can you run `npm run lint:fix` to fix the formatting?

**Comment by gczobel-f5** [comment]
> 
> 
> @gczobel-f5 thanks for the contribution! Can you run `npm run lint:fix` to fix the formatting?
@nabdelgadir  Done

**Comment by bajtos** [comment]
Landed, thank you @gczobel-f5 for the contribution!

**Pull request merged**
