### PR TITLE
feat: add an example to illustrate binding resolution and injection within a context hierarchy

### PR DESCRIPTION
**Pull request by raymondfeng**
See https://github.com/strongloop/loopback-next/blob/example-binding-resolution/examples/binding-resolution/README.md for docs.

Related to https://github.com/strongloop/loopback-next/issues/6325

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
FYI: I'll update this example application once https://github.com/strongloop/loopback-next/pull/6333 is landed.

**Comment by bajtos** [comment]
I am concerned about the growing number of example packages we have. Each new package is adding a bit of overhead to `npm install`, `npm build` and `npm test` times, thus incrementally slowing our local development and CI builds.

Have you considered to add your new examples to the existing context-related example package [examples/context](https://github.com/strongloop/loopback-next/tree/master/examples/context/src)? 

To better separate different example scenarios, we can create a subdirectory in `examples/context/src` to hold all related files, e.g. `examples/context/src/binding-resolution/README.md`, `examples/context/src/binding-resolution/controllers`, etc.

WDYT?

**Comment by raymondfeng** [comment]
@bajtos I have considered to place it inside `examples/context` but realized the new example will have `@loopback/rest` dependency for e2e http calls. Please note that `examples/context` was intentionally created to have `@loopback/context` dependency only to illustrate the possibility to use it as a standalone IoC/DI library.

**Comment by bajtos** [comment]
> @bajtos I have considered to place it inside `examples/context` but realized the new example will have `@loopback/rest` dependency for e2e http calls. Please note that `examples/context` was intentionally created to have `@loopback/context` dependency only to illustrate the possibility to use it as a standalone IoC/DI library.

That's a legitimate reason for creating a new example package :+1: Thanks for explaining!

**Review by bajtos — APPROVED** [review]
I quickly skimmed through the proposal and don't see any obvious problems. I'll leave the detailed review to Context code owners.

**Review by jannyHou — APPROVED** [review]
👍 LGTM, nice to have example showing the context hierarchy.

**Pull request merged**
