### PR TITLE
Leverage built-in async support in autocannon + include bechmark tests in the test suite 

### PR DESCRIPTION
**Pull request by bajtos**
-  Ensure the benchmarks pass their own tests. Note that we ARE NOT running the actual benchmarks.
-  ~~upgrade autocannon to 4.0.0 and~~ leverage their new support for promises (see https://github.com/mcollina/autocannon/pull/205).

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@bajtos CI is failing - https://travis-ci.org/strongloop/loopback-next/jobs/539724565. I wonder if it's too expensively to run it as part of `npm test`.

**Comment by bajtos** [comment]
> CI is failing - https://travis-ci.org/strongloop/loopback-next/jobs/539724565. I wonder if it's too expensively to run it as part of npm test.

Let me try to bump up the timeout. AFAICT, LB4 applications are very slow to start, that's why the test takes so long.

**Comment by raymondfeng** [comment]
Hmm:
```
1) Benchmark (SLOW)
       works:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/travis/build/strongloop/loopback-next/benchmark/dist/__tests__/benchmark.integration.js)
```

**Comment by bajtos** [comment]
Hmm, I am not comfortable to add such a slow test to our test suite that's already running longer than I would like.

I am going to remove the change in top-level `package.json` and keep the benchmark tests outside of the main test suite. (I am fully aware that this means the tests may break again in the future and we don't notice.)

I'd still like to land the rest of this pull request though:
- fix `npm test` inside `bechmark`
- drop `util.promisify`

**Pull request merged**
