### PR TITLE
Update todo-list-tutorial-sqldb.md

### PR DESCRIPTION
**Pull request by odykyi**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by odykyi** [comment]
@achrinza `onDelete` works good - creates correctly values for cascade, but `onUpdate` not creates values, I think its a bug with `onUpdate`

**Comment by emonddr** [comment]
@odykyi , please provide a paragraph explaining the purpose of your PR, and why the doc needs updating. Including document links pertaining to the entries you are adding:

```
onUpdate: 'restrict',
onDelete: 'cascade',
```

and mocha test cases proving these work.

Thx

**Comment by emonddr** [comment]
Only thing I found on cascade was an old comment: https://github.com/strongloop/loopback-connector-postgresql/issues/348#issuecomment-455070720 .

**Comment by emonddr** [comment]
I found, for mysql connector as @achrinza  mentioned:

https://github.com/strongloop/loopback-connector-mysql/blob/cdc800875bfb6392041e26d92915b71292afb1ed/lib/migration.js#L504 

https://loopback.io/doc/en/lb4/MySQL-connector.html#auto-migrateauto-update-models-with-foreign-keys

**Comment by emonddr** [comment]
> @achrinza `onDelete` works good - creates correctly values for cascade, but `onUpdate` not creates values, I think its a bug with `onUpdate`

@odykyi which connector does the statement above apply to? : mysql or postgresl? If you identify a connector bug please open up against the appropriate connector repository and provide a mocha test that shows the failure. Thank you. :)

**Comment by achrinza** [comment]
Hi @odykyi, just checking in; are you still interested in pursuing this PR?

**Comment by achrinza** [comment]
Closing due to inactivity.

**Pull request closed without merging**
