### PR TITLE
feat(example-coffeeshop): add coffeeshop example

### LINKED ISSUE #635: Create a LB4 version of CoffeeShop app
Per our discussion this morning:
In LB3, we have CoffeeShop app as one of the example app.  
It would be nice to have a similar app using LB4. 
LB3 CoffeeShop make sure of CLI.  Having similar app in LB4 can guide us on what is needed for Tooling GA.

### PR DESCRIPTION
**Pull request by derdeka**
Implements coffeeshop as example, migrated from https://github.com/strongloop/loopback-getting-started-intermediate

Fixes #635
Related to #4610

After commiting i discoverd that @dhmlau did already something similar: https://github.com/dhmlau/loopback4-coffeeshop/

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@derdeka Do you plan to consolidate with https://github.com/dhmlau/loopback4-coffeeshop/ and port the UI from LB3 as well?

**Comment by derdeka** [comment]
> @derdeka Do you plan to consolidate with https://github.com/dhmlau/loopback4-coffeeshop/ and port the UI from LB3 as well?

The initial idea was to build the `angular` example on top of this `lb4` example.

**Comment by dhmlau** [comment]
@derdeka, are you looking into this https://github.com/strongloop/loopback-next/issues/4849 too? This is to create a tutorial to go from LoopBack to Angular. Thanks.

**Comment by bajtos** [comment]
Thank you @derdeka for the pull request. I like the idea of having an example app showing a full stack LoopBack + Angular application ❤️ 

Ideally, I would like such app show not only how to write the app, but also include proper test suite including end-to-end tests executed in the browser.

Now running tests in a browser is a bit involved, I am reluctant to include such tests in loopback-next - I am concerned about extra duration they would add to our already slow test suite.

Personally, I would prefer to create a dedicated repository for this example application.

Thoughts?

**Comment by bajtos** [comment]
@dhmlau  I have assigned you as the primary reviewer, feel free to bring other core team members to help with the review. (Do we have anybody familiar with Angular on our team?)

**Comment by dhmlau** [comment]
We just switch the contribution method from CLA to DCO, making your contribution easier in the future. Please sign the commits with DCO by amending your commit messages with `-s` flag and push the changes again. If you're using the command line, you can:

```
git commit --amend -s
git push --force-with-lease
```

Please refer to [this docs page](https://loopback.io/doc/en/contrib/code-contrib.html#developer-certificate-of-origin-dco) for details. Thanks!

**Pull request closed without merging**
