### PR TITLE
Use testlab 4.0.0-alpha.2 in all packages

### PR DESCRIPTION
**Pull request by superkhau**
cc @bajtos @raymondfeng @ritch

### CODE REVIEW

**Comment by bajtos** [comment]
FWIW, updates like this should not be needed. The version specifier `^4.0.0-alpha.1` includes all newer alphas.

```
$ semver -r "^4.0.0-alpha.1" 4.0.0-alpha.1 4.0.0-alpha.2 4.0.0-beta.1
4.0.0-alpha.1
4.0.0-alpha.2
4.0.0-beta.1
```

I think we may need to run `lerna clean --yes && lerna bootstrap` to force `lerna` to update existing projects.

**Comment by superkhau** [comment]
@bajtos :thailand: Annoyingly, this was all done manually and needed to make everything pass. In the future once [we confirm at lerna publishing works as expected](https://github.com/strongloop/loopback-next/issues/250), then I'm all for just `lerna publishing` and having it to do the subpackage updates for us.

**Comment by bajtos** [comment]
@superkhau I think you misunderstood my point. I am saying that in most cases we don't need to change `^4.0.0-alpha.1` to `^4.0.0-alpha.2` in the same way we don't need to change `^1.2.3` to `^1.2.4`, because `npm install` is going to pick the latest version anyways.

I guess the most notable exception is when a dependency is adding a new feature that a dependent is relying on, in which case it makes sense to bump up the minimum required version.

**Comment by bajtos** [comment]
Anyways, it's not a big deal, let's focus on more pressing concerns.

**Comment by superkhau** [comment]
@bajtos Yes, I misunderstood what you meant. Just ran the command like you showed above and it picks up all the versions as you described. +1 for no more manual updates like this. ;)

**Pull request merged**
