### PR TITLE
feat(cli): april translation drop

### PR DESCRIPTION
**Pull request by zenjerr**
feat(cli): april drop

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@zenjerr, thanks for the PR. Could you please sign the DCO? You can do so by running the following command: 
```
git comment --amend -s
```

Thanks.

**Comment by zenjerr** [comment]
@dhmlau , I just signed the DCO (not sure if I did it correctly or not). Let me know if it's not okay.

**Comment by dhmlau** [comment]
FYI - I squashed the commits but DCO bot still complained. I ran the following commands and fixed the problem:

```
git commit --amend --no-edit --signoff
git push --force-with-lease origin transl/webfm-0414-042637
```

**Review by agnes512 — APPROVED** [review]

**Comment by dhmlau** [comment]
@zenjerr, thanks for your contribution. Your PR has landed! 🎉

**Pull request merged**
