### PR TITLE
docs(examples): re-phrase overview introduction in 'log-extension' README

### PR DESCRIPTION
**Pull request by ddsultan**
*Suggestion*

**Rationale**: the document is more about building an **extension** (with Component, Decorator and Mixen) than using *the CLI*

Signed-off-by: ddsultan <2477698+ddsultan@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@ddsultan Thank you for the PR.

There are two minor issues to be fixed before we can land it:

1. Change the commit message to be something like: `docs(example-log-extension): ...`
2. Run `npm run prettier:fix` to fix the file formatting.

**Comment by ddsultan** [comment]
> @ddsultan Thank you for the PR.
> 
> There are two minor issues to be fixed before we can land it:
> 
> 1. Change the commit message to be something like: `docs(example-log-extension): ...`
> 2. Run `npm run prettier:fix` to fix the file formatting.

@raymondfeng, My pleasure. 

1. I thought something like this at first because it felt a bit verbose yet this would make a commit message specific and easier to understand. Or do you think there are more advantages to have the example name?
2. I didn’t know about this. What would be the advantage of using prettier with Markdown here? Fixing Line Endings?

I will make the changes as requested. Thanks for the feedback.

**Comment by raymondfeng** [comment]
> I thought something like this at first but it felt a bit verbose yet this would make the commit message more specific and easier to understand. Or do you think there are more advantages to have the example name?

Feel free to use `docs: ...` in this case.

> I didn’t know about this. What would be the advantage of using prettier with Markdown here? Fixing Line Endings?

It helps format the line width, embedded code, and a few style conventions.

**Comment by nflaig** [comment]
@ddsultan, Thanks for your contribution.

**Pull request merged**
