### PR TITLE
Added support for yarn, fixing tests for windows and added lint:fix s…

### PR DESCRIPTION
**Pull request by el-davo**
Hi, Not sure if you guys know about yarn but i think it might help speed up the npm install process, it will also ensure that everyone has the exact same dependencies of everything, including subdependencies. https://yarnpkg.com/en/

I also noticed that the npm test command doesnt work on windows (windows 10 at least). I have fixed that and added a new task to fix lint errors, because I like to automate all as much as I can. Feel free to reject this pr but yarn has really helped us scale large projects that run into npm dependency issues.

I believe lerna are also trying to switch to yarn - https://github.com/lerna/lerna/issues/371

Some benchmarks on my windows 10 machine

npm install - 40s
Yarn install with no cache - 33s
Yarn install with cache - 6s

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@el-davo I've looked a bit into yarn and don't have any objections yet. It would be nice to support both NPM and Yarn, but we'll have to do a bit of research before landing anything concrete IMO.

cc @rayesk @bajtos @ritch Thoughts?

**Comment by bajtos** [comment]
+1 for fixing `npm test` on windows (we were already keeping track of that issue in #164) and adding `npm run lint:fix` script

I am personally against using `yarn`. I understand the value `yarn` brings to projects developing an application, where all dependencies (including dev dependencies) are locked down to a specific version number and updated manually. However, loopback is a module that's shipped with `package.json` containing loose dependency versions, so that people installing loopback always get the latest version of our dependencies and we don't have to make a new framework release everytime a dependency or a dependency of our dependency changed.

My concern is that if we start using `yarn`, we will be locally working with outdated versions of our dependencies and won't be able to catch a whole category of problems.

Having said that, if we agree that `yarn` is the way forward, then we must ensure that `npm install @loopback/core` installs the very same set of dependencies as we are/were installing using `yarn` during dev/CI.

Either way, I think `yarn` is a longer conversation to have. Let's leave it out of scope of this pull request and discuss `yarn` vs. `npm` in a new issue. That way we can land non-controversial  improvements ASAP: windows fix + autofixing linter.

**Comment by el-davo** [comment]
@bajtos Agreed, I was actually giving this second thoughts based on how the project is setup. Ive never actually used lerna but after looking into how it works it looks like yarn would have to first be working with lerna and then rolled out to all repositories at the same time. Thanks for the comments

I will reject this pr and open a new one with just the windows and lint:fix task.

**Pull request closed without merging**
