### PR TITLE
Farewell 👋

### PR DESCRIPTION
**Pull request by bajtos**
With a bit of sadness I'd like to share with you my personal news. Today is my last day at IBM and that's also the end of my journey with LoopBack. 😢

It was great to build the framework from the initial 1.0 version back in 2013 to the new TypeScript-based version 4.0, I learned a lot along the way. It was even better to build the community surrounding this project, you are awesome! 🤗 

All good things have to come to an end, and so the time came for me to close this chapter of my life. I'll miss you all. ❤️ 

On the bright side, I hope you - the members of the LoopBack community - will use this change as an opportunity to grow your involvement with the project, bring fresh ideas and new perspectives unencumbered by the limitations of the past, and make the project fly even higher! 🚀

### CODE REVIEW

**Comment by dougal83** [comment]
Sorry to hear this news. I hope that you and your family are in good health and wish you all the best. I hope the community can fill Mr Loopback's shoes in his absence and take the project to new heights. Best wishes.

**Comment by raymondfeng** [comment]
@bajtos It's sad to see you leave IBM and this community. But we appreciate your significant contributions and leadership! Best wishes for your future journey!

**Comment by frbuceta** [comment]
Thanks for all the help you have given me @bajtos. I admire your job

**Comment by achrinza** [comment]
Thank you @bajtos for all of the help contributions to LoopBack throughout the years! Best wishes in your future endeavours. :heart:

**Comment by marioestradarosa** [comment]
@bajtos , beyond the software engineering, **you are a great human being,** thank you for all the guidance in my initial steps with the framework and because despite of all your knowledge you were always there to give a hand to us the beginners, thank you from all of us, thank you , thank you.

I wish you the best in all your future projects and be aware that we will follow your Tweets :-)

**Pull request merged**
