### PR TITLE
Update todo-tutorial-putting-it-together.md

### PR DESCRIPTION
**Pull request by siosio34**
If use
```
import {db} from './datasources/db.datasource';
```
then
```
make error src/application.ts(4,9): error TS2305: Module '"/src/datasources/db.datasource"' has no exported member 'db'
```
because src/datasources/db.datasource export DbDataSource not 'db'

so you 
```
 import {DbDataSource} from './datasources/db.datasource';
```
and
```
 const datasource =
      this.options && this.options.datasource
        ? new juggler.DataSource(this.options.datasource)
        : DbDataSource;
```

## Checklist

- [X] `npm test` passes on your machine
- [X] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [X] API Documentation in code was updated
- [X] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [X] Affected artifact templates in `packages/cli` were updated
- [X] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by virkt25** [comment]
Thanks for the PR @siosio34 !! 

There's some more changes I would like to see along with this PR. Since we now have a `Booter` for `DataSources`, that code is actually no longer needed. Can you do the following:

- Remove `setupDatasources()` and the call to the function from the constructor
- Remove the import statement.

**Comment by virkt25** [comment]
Oh, and can you please update the commit message to be 100 characters or less on each line so the commit linter passes.

**Comment by siosio34** [comment]
OK !! i will new pull request this project with your feedback ~
thank you so much advice

**Comment by siosio34** [comment]
please close this pull request

**Pull request closed without merging**
