### PR TITLE
chore(core): set max listeners to 256 for `process` to avoid warnings

### PR DESCRIPTION
**Pull request by raymondfeng**
Step 2 for #5011 

Increase number of process listeners to avoid warnings.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by bajtos** [comment]
When we disable max-listener warnings in our tests, then we won't notice if our code is leaking event listeners.

IMO, we should avoid changing the global max-listener configuration at all costs and look for ways how to change max-listeners config in specific places (on specific event emitter instances) only.

**Comment by boneskull** [comment]
Which listeners do you mean?

Mocha isn’t listening for SIGINT more than once or twice. I was thinking those came out of LB (or a dep)

**Comment by boneskull** [comment]
but fwiw I wouldn’t recommend bumping it either, unless we can show that it’s _not_ a leak and they won’t grow further

**Comment by raymondfeng** [comment]
Close to favor https://github.com/strongloop/loopback-next/pull/5020

**Pull request closed without merging**
