### PR TITLE
doc: fix broken link in authentication

### PR DESCRIPTION
**Pull request by srl295**
broken link in the packages/authentication/README.md

## Checklist

- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated

### CODE REVIEW

**Comment by dhmlau** [comment]
@srl295 , good catch.  Could you please sign the CLA so that we can accept your changes? https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by srl295** [comment]
@dhmlau tried, the last button to sign gives a

> 504 ERROR

**Comment by dhmlau** [comment]
Strange. It shows that you've signed already.
Could you please rebase the PR?

**Comment by dhmlau** [comment]
There's a commit linter error: 
```
⧗   input: doc: fix broken link in authentication
✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
✖   found 1 problems, 0 warnings 
    (Need help? -> https://github.com/conventional-changelog/commitlint#what-is-commitlint )
```

My suggested change to your commit message would be
```
fix(authentication): fix broken link in authentication docs
```

For details, please see https://loopback.io/doc/en/contrib/code-contrib-lb4.html#commit-message-guidelines

**Comment by dhmlau** [comment]
@srl295 , thanks for your contribution.  Your PR has landed! 🎉

**Pull request merged**
