### PR TITLE
[DO NOT MERGE] feat(cli): extract messages for application generator

### PR DESCRIPTION
**Pull request by dhmlau**
Related to spike https://github.com/strongloop/loopback-next/issues/2428. 

This PR has changes needed to extract messages for the application generator only.

#### Code changes
- Using similar implementation in `generator-loopback` module. e.g. https://github.com/strongloop/generator-loopback/blob/master/lib/globalize.js.
- Reviewers: If the PR is good, I'll remove `intl/zh-Hans/messages.json` and `intl/zh-Hant/messages.json` which are only used for testing purpose. 

#### Sniff test
I used a dummy `intl/zh-Hans/messages.json` to test.  Here is the output. Please see the string prefixed with `中文` means they are coming from that translation file.

```
$ lb4 app
? 中文Project name: translation-test5
? 中文Project description: loopback4 example
? 中文Project root directory: translation-test5
? 中文Application class name: TranslationTest5Application
? 中文Select features to enable in the project (Press <space> to select, <a> to toggle all, <i>
...

中文Application translation-test5 was created in translation-test5.

中文Next steps:

$ cd translation-test5
$ npm start

```

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
> I think we should globalize & translate error messages too in addition to prompts.

@bajtos, do you mean error messages in other packages?

**Comment by dhmlau** [comment]
> We might want to use g.f for other prompts too ( not in this PR).

@agnes512, yes. After this one lands, I will work on changes for other generators. Thanks!

**Comment by raymondfeng** [comment]
@dhmlau Please rebase the PR against latest master to get rid of irrelevant `package-lock.json` changes.

**Comment by raymondfeng** [comment]
Can we add a test to verify it works with a different locale?

**Comment by dhmlau** [comment]
A few points from @raymondfeng:
1. Measure the overhead of strong-globalize and fix bottlenecks if possible
2. Have a build step to regenerate messages.json for English if any code change for cli
3. Add a test to make sure globalization is working correctly
4. Can we start with a new branch or a npm dist tag for translation?

As the next step, I'll work on #1, i.e. measure time taken to run `npm test` on `@loopback/cli` with and without the strong-globalize change. 

----

For adding tests, I'd prefer to have the messages.json translated so that we will have the real test results in the future. Will get the measurement done first and see if the current strong-globalize approach is the one that we want.

**Comment by nabdelgadir** [comment]
(Sorry approved before seeing latest discussion, will review again when it's ready for review )

**Comment by dhmlau** [comment]
@raymondfeng , per your request, I've run some tests to see how long it takes to finish the tests in the `cli` package with and without using the translated messages through `strong-globalize`.  To show a bigger differences (hopefully), I've made modifications in other generators as well. The changes are not complete but here are my results. I got the time from running `time npm test` under `packages/cli`

### Without strong-globalize
**Trial 1**
real	1m51.811s
user	2m23.815s
sys	0m18.518s

**Trial 2**
real	1m57.407s
user	2m30.606s
sys	0m17.867s


### With strong-globalize
**Trial 1**
real    1m53.238s
user    2m27.353s
sys     0m19.635s

**Trial 2**
real    2m5.382s
user    2m41.054s
sys     0m19.671s

Please advise on the next steps. Thanks.

**Comment by dhmlau** [comment]
Discussed the test results with @raymondfeng. It seems like using strong-globalize is the only viable option right now.  So we'll go in this direction.

**Comment by dhmlau** [comment]
Sorry that I need to abandon this PR because I wasn't able to rebase the branch properly. 😞 
Opened https://github.com/strongloop/loopback-next/pull/4568 for the previously approved content.

**Pull request closed without merging**
