### PR TITLE
Change 'cd' to change to the right directory: loopback4... not loopba…

### PR DESCRIPTION
**Pull request by robblovell**
A simple change to the documentation so that it works.

### CODE REVIEW

**Comment by raymondfeng** [comment]
@robblovell Thanks for the fix. Please sign CLA - https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by raymondfeng** [comment]
The commit message needs to be fixed too:
```
⧗   input: Change 'cd' to change to the right directory: loopback4... not loopback...
✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
The command "/bin/bash ./bin/lint-commits.sh" exited with 1.
```

**Comment by b-admike** [comment]
you can to refer [here](https://github.com/strongloop/loopback-next/blob/master/docs/DEVELOPING.md#commit-message-guidelines) for our commit guidelines.

**Comment by bajtos** [comment]
@robblovell ping 🔔 What's the status of this pull request? Could you please sign our Contributor License Agreement? We cannot proceed without that.

https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by raymondfeng** [comment]
The issue is fixed at https://github.com/strongloop/loopback-next/blob/master/packages/example-getting-started/README.md#try-it-out now.

**Pull request closed without merging**
