### PR TITLE
docs: fix hasMany diagram L&F

### PR DESCRIPTION
**Pull request by dhmlau**
Change the L&F of the [hasMany diagram ](https://loopback.io/pages/en/lb4/imgs/hasMany-relation-example.png) to something similar to the[ todo overview digram](https://loopback.io/pages/en/lb4/imgs/todo-overview.png).

Fixes https://github.com/strongloop/loopback-next/issues/1532

### CODE REVIEW

**Comment by marioestradarosa** [comment]
How about this one? . I think the **customerId** on Order table should be number.

er_diagram_lb4

**Comment by dhmlau** [comment]
@marioestradarosa , thanks for catching the error.  I like your diagram!  
May I know what software do you use to create the diagram?  Cannot find the arrow style in PowerPoint.

We're trying to use these color palettes for the LB4 documentation diagrams.  If you could modify your diagram using those colors (I think only the green is off?), please feel free to submit another PR, I'm happy to abandon this one.

**Comment by marioestradarosa** [comment]
@dhmlau I used Keynote and the many arrow is coming from one of the connectors (_actually you have to mold it a little bit_). I am color blind, so I think I never saw the green line :-) . don't worry about the PR you can use the diagram on this PR.  If you want me to send you the KeyNote file, I will send it to you.

lb4_er_cust_order 001

**Comment by b-admike** [comment]
Thank you for fixing this @dhmlau @marioestradarosa, the new one is looking great 👍

**Comment by dhmlau** [comment]
Thanks @marioestradarosa. I've updated with your diagram.

**Comment by dhmlau** [comment]
Thanks @marioestradarosa.   The PR has merged. :)

**Pull request merged**
