### PR TITLE
docs: change OASGraph to OpenAPI-to-GraphQL

### PR DESCRIPTION
**Pull request by Alan-Cha**
Updated documentation to reflect the name change from OASGraph to OpenAPI-to-GraphQL. 

I also manually tested the Exposing GraphQL APIs tutorial and it works with the updated commands. 

***

~~I could not get the tests to work even though all I did was change some comments and a markdown file.~~

~~I think I have some issues with Prettier in the markdown file but I'm a bit lost on how to address it.~~

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback-next@0.1.0 prettier:cli: `node packages/build/bin/run-prettier "**/*.ts" "**/*.js" "**/*.md" "-l"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-next@0.1.0 prettier:cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan.cha/.npm/_logs/2019-07-15T18_11_57_235Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback-next@0.1.0 prettier:check: `npm run prettier:cli -- -l`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-next@0.1.0 prettier:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan.cha/.npm/_logs/2019-07-15T18_11_57_256Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback-next@0.1.0 lint: `npm run prettier:check && npm run eslint && node bin/check-package-locks`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-next@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan.cha/.npm/_logs/2019-07-15T18_11_57_281Z-debug.log
npm ERR! Test failed.  See above for more details.
```

Edit: tests work now after reformatting!

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by nabdelgadir** [comment]
Run `npm run lint:fix` to fix the formatting issues.

**Comment by Alan-Cha** [comment]
@nabdelgadir Thanks! That did the trick!

**Comment by dhmlau** [comment]
@nabdelgadir, for the corresponding tutorial on IBM Developer, we might need to update accordingly as well. Could you please take care of that? Thanks.

**Comment by dhmlau** [comment]
@Alan-Cha, thanks for updating the docs. Your PR has landed. 🎉

**Pull request merged**
