### PR TITLE
Replace eslint rule `no-invalid-this` with TypeScript-aware one

### PR DESCRIPTION
**Pull request by bajtos**
See https://github.com/typescript-eslint/typescript-eslint/issues/604

The first commit changes our eslint config, the second removes `eslint-disable` comments that are no longer necessary 🎉 

**BREAKING CHANGE**

In code accessing `this` variable, eslint-ignore comment for `no-invalid-this` will no longer work. You can either change those comments to disable `@typescript-eslint/no-invalid-this`, or better tell TypeScript what is the type of `this` in your function.

A TypeScript example:

```ts
describe('my mocha suite', function(this: Mocha.Suite) {
  this.timeout(1000);
  it('is slow', function(this: Mocha.Context) {
    this.timeout(2000);
  });
})
```

A JavaScript example:

```js
describe('my mocha suite', /** @this {Mocha.Suite} */ function() {
  this.timeout(1000);
  it('is slow', /** @this {Mocha.Context} */ function() {
    this.timeout(2000);
  });
})
```

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by bajtos** [comment]
Hmm, this didn't work out as well as I expected. VS Code was not showing any linting errors to me, but `npm run lint` did. I'll need to investigate.

**Comment by bajtos** [comment]
Fixed, the PR is ready for review & landing.

**Comment by raymondfeng** [comment]
@bajtos CI is failing. Some TS syntax is used in JS files.

**Comment by bajtos** [comment]
> CI is failing. Some TS syntax is used in JS files.

Sorry for that, I have rebased the patch on top of the latest master and fixed the problems in 6d8528d

@raymondfeng LGTY now?

**Pull request merged**
