### PR TITLE
Implement eslint-plugin-jsdoc (only for loopback monorepo)

### PR DESCRIPTION
**Pull request by frbuceta**
Today I changed editor and I have noticed that the JSDoc are not good in some cases. So I want you to think what you think of this.

It is only for the monorepo, not for the general configuration @strongloop/loopback-maintainers 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dougal83** [comment]
Hey @frbuceta , please excuse my ignorance in this area but what does this add to the project? Is it different to [tsdocs](https://loopback.io/doc/en/lb4/apidocs.tsdocs.html)? As I understand it, the tool picks up comments in code and compiles web pages essentially containing the comments.

**Comment by frbuceta** [comment]
> Hey @frbuceta , please excuse my ignorance in this area but what does this add to the project? Is it different to [tsdocs](https://loopback.io/doc/en/lb4/apidocs.tsdocs.html)? As I understand it, the tool picks up comments in code and compiles web pages essentially containing the comments.

This checks that you write JSDocs correctly. Now you can see [here](https://travis-ci.com/github/strongloop/loopback-next/jobs/331026081) that many are not well ... that's why the tests fail

**Comment by raymondfeng** [comment]
@frbuceta I suggest that we add the `jsdoc` rule to a separate file and have the main `.eslintrc.js` to extend from it and the TS one. It might only be useful for `*.js` files.

The jsdoc rule does not apply to most TS files. For example, the tsdoc can infer param and return types. Tsdoc discourages to specify types in comments for such elements. For example,

```ts
/**
 * @param x - X
 * @param y - Y
 */
function (x: string, y: number) {
}
```

It's perfectly fine for tsdcos, but jsdoc plugin complains that `x` and `y` are missing types.

**Comment by bajtos** [comment]
> @frbuceta I suggest that we add the `jsdoc` rule to a separate file and have the main `.eslintrc.js` to extend from it and the TS one. It might only be useful for `*.js` files.
> 
> The jsdoc rule does not apply to most TS files. For example, the tsdoc can infer param and return types. Tsdoc discourages to specify types in comments for such elements. For example,
> 
> ```ts
> /**
>  * @param x - X
>  * @param y - Y
>  */
> function (x: string, y: number) {
> }
> ```
> 
> It's perfectly fine for tsdcos, but jsdoc plugin complains that `x` and `y` are missing types.

Recently, API Extractor was enhanced (fixed?) to recognize even shorter syntax:

```ts
/**
  * @param x Description of param x
  * @param y Description of param y
  */
 function (x: string, y: number) {
 }
```

See https://github.com/microsoft/tsdoc/pull/206.

Can we use [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc) to validate our tsdoc comments? This plugin is officially recommented by tsdoc (see [here](https://github.com/microsoft/tsdoc#how-do-i-get-started-with-tsdoc)). tsdoc is powering api-extractor that we are using to build our api docs.

**Comment by bajtos** [comment]
@frbuceta I love the idea of linting our tsdoc comments ❤️ I am never sure if I am writing those comments correctly and most of the time I am too lazy to check how they are rendered in our API docs, so having an automated linter would be great 👏

**Comment by raymondfeng** [comment]
> Recently, API Extractor was enhanced (fixed?) to recognize even shorter syntax:

Yes, I realized that. I would say it's a fix :-).

**Comment by frbuceta** [comment]
I close this? @raymondfeng is doing it in another PR

**Comment by frbuceta** [comment]
> @frbuceta I love the idea of linting our tsdoc comments ❤️ I am never sure if I am writing those comments correctly and most of the time I am too lazy to check how they are rendered in our API docs, so having an automated linter would be great 👏

I love that you like it

**Comment by bajtos** [comment]
> I close this? @raymondfeng is doing it in another PR

I think that would be best. You can always reopen this PR in the future in case #5435 goes nowhere.

**Pull request closed without merging**
