### PR TITLE
perf(repository): prevent multiple array allocation

### PR DESCRIPTION
**Pull request by Yaty**
An improvement I found possible while looking at the code :)

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by raymondfeng** [comment]
@Yaty Thank!

**Comment by bajtos** [comment]
Thank you @Yaty for the contribution ❤️ 

I think it would be even better to move the array `nonWhereFields` out of `impose` method because it's constant and never changes. This should save even more memory allocations.

**Comment by Yaty** [comment]
I can send a PR this weekend for that !

**Comment by bajtos** [comment]
> I can send a PR this weekend for that !

@Yaty lovely, I am looking forward to your new PR 👍

**Pull request merged**
