### PR TITLE
chore: update release name

### PR DESCRIPTION
**Pull request by dhmlau**
When we are ready to release Developer Preview 2, we need to update the status on the readme files.
Change the release name for:
- `README.md`
- `packages/rest/README.md`

connected to: https://github.com/strongloop/loopback-next/issues/1059

Will merge when we are ready.

### CODE REVIEW

**Comment by virkt25** [comment]
Either all of the packages should have a status or just the top level.

**Comment by dhmlau** [comment]
I was actually thinking about adding the status for each of the packages, because each package is a separate node module on npmjs.  But it might also mean redundant information when we're looking at the monorepo level.  

Are we good with adding the same text from the top level readme? 
```
## Status: Developer Preview #1

LoopBack 4 is a work in progress, the public API is frequently changed in
backward incompatible ways. See
[Upcoming-Releases on wiki](https://github.com/strongloop/loopback-next/wiki/Upcoming-Releases)
for more details.

Learn about the latest and greatest
[features and technologies in LoopBack 4](https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html)
by using it for your next project. Start by having a look at
[Getting Started](https://loopback.io/doc/en/lb4/Getting-started.html).

**NOTE:** _It is not recommended for production use yet._ For production, use
[LoopBack 3](https://loopback.io/doc/en/lb3/index.html).
```

**Comment by virkt25** [comment]
I personally think it's best to just have that at the top level for the mono-repo ... and the version number (`0.x.y`) should be indicative of this to not be used in production. 

But if you were to add that message to all packages, that's fine too

**Comment by dhmlau** [comment]
I'm good with having one status!

**Pull request merged**
