### PR TITLE
feat: enable injection at lifecycle time

### PR DESCRIPTION
**Pull request by mdbetancourt**
Implements #6643

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [] `npm test` passes on your machine
- [] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by mdbetancourt** [comment]
@raymondfeng @bajtos i found an error at examples/binding-resolution/src/interceptors/spy.interceptor.ts i think is because when i called invokeMethod the global intersector is called but server is not ready yet so it throws `Error: Binding "server.counter" in context "InterceptedInvocationContext-hRmeFTG0Q5y40R7jjI-rnw-3" cannot be resolved in scope "Server"` should i skip interceptors for lifecycle?

**Comment by raymondfeng** [comment]
@mdbetancourt What's your use case to enable dependency injection/interception for lifecycle methods?

1. Dependency injection can be done at class constructor/property level as life cycle observers are singletons. 
2. Applying interceptors for life cycle methods can be dangerous as the application is not fully prepared/initialized/bootstrapped yet.

**Comment by mdbetancourt** [comment]
> 2. Applying interceptors for life cycle methods can be dangerous as the application is not fully prepared/initialized/bootstrapped yet.
that's what i am asking if should i skip interceptors for lifecycle.
now i wanna add dep injection for lifecycle for:
1. get consistency (dep injection is allowed almost everywhere but not there some people probably expect to just work there too)
2. scoped (sometimes we only need some deps just once for example repository getters for resolvers)
3. when you are using mixins constructors looks like (constructor(...args: any[])) so you cant use injections there now if you use a lifecycle like init or start then you need make it a class property polluting the object when probably you arent gonna need that injection anymore
5. is not too hard to implement it's just call "invokeMethod" instead of call the function directly (disabling interceptors)

**Comment by raymondfeng** [comment]
1. For `invokeMethod`, you can use `options.skipInterceptors` to skip interceptors.

2. We intentionally don't allow method parameter injections for certain APIs, such as `Provider.value()`, `LifeCycleObserver.init/start/stop` as the dependency injection can happen at class constructor/property level. To allow injections, we need to define such methods to be something like `init(...args: unknown[])`.

3. If you can give an example that we cannot implement without this PR, we can assess.

**Comment by mdbetancourt** [comment]
> 3\. If you can give an example that we cannot implement without this PR, we can assess.

this is more focused to developer experience and maybe sometimes when some injection is not available at constructor level (if something need to be started) but you can use a getter

**Comment by raymondfeng** [comment]
@mdbetancourt Based on the discussion, I created an improved PR at https://github.com/strongloop/loopback-next/pull/6740. Please check if that's what you need.

**Comment by mdbetancourt** [comment]
@raymondfeng yes it is, closing this

**Pull request closed without merging**
