### PR TITLE
feat(eslint-config): enable return-await

### PR DESCRIPTION
**Pull request by bajtos**
Require users to await a promise before returning the result inside a `try` block. Otherwise the errors won't be caught by the catch block.

Require users to NOT await a promise when the result is immediately returned outside of a `try` block. This is a (micro)performance optimization to avoid unnecessary allocation of an extra Promise instance.

Rule docs: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md

~~At the moment (2019-11-28), eslint reports false positives, they should be fixed by https://github.com/typescript-eslint/typescript-eslint/pull/1270. This pull request cannot be landed until that patch is released & our package-lock files are updated with the new version of the eslint plugin.~~ 
The eslint fix was released in [v2.10.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.10.0).

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by bajtos** [comment]
@raymondfeng @strongloop/loopback-next WDYT, should we release this change as semver-major?

**Comment by raymondfeng** [comment]
Please fix the following violations:
```
/home/travis/build/strongloop/loopback-next/examples/context/src/custom-configuration-resolver.ts
  47:7  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/boot/src/__tests__/fixtures/interceptor.artifact.ts
  49:7  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/boot/src/__tests__/fixtures/non-global-interceptor.artifact.ts
  49:7  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/cli/lib/base-generator.js
  74:7  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/cli/test/snapshot-matcher.js
  170:5  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/context/src/__tests__/acceptance/interceptor.acceptance.ts
  696:7  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/repository/src/query.ts
  663:7  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/rest/src/body-parsers/body-parser.ts
  64:9  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
/home/travis/build/strongloop/loopback-next/packages/rest/src/coercion/coerce-parameter.ts
  191:5  error  returning an awaited promise is required in this context  @typescript-eslint/return-await
```

**Comment by bajtos** [comment]
> Please fix the following violations

See the PR description:

> At the moment (2019-11-28), eslint reports false positives, they should be fixed by https://github.com/typescript-eslint/typescript-eslint/pull/1270. This pull request cannot be landed until that patch is released & our package-lock files are updated with the new version of the eslint plugin.

The eslint fix was released in [v2.10.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.10.0), we are good to proceed now.

**Comment by bajtos** [comment]
Hmm, it looks like there are still some false positives reported by eslint:

```
/home/travis/build/strongloop/loopback-next/extensions/metrics/src/interceptors/metrics.interceptor.ts
88:7  error  returning an awaited value that is not a promise is not allowed  @typescript-eslint/return-await
```

The code:

https://github.com/strongloop/loopback-next/blob/4478f736e39aef68789834c8e77d4f3f7d933f68/extensions/metrics/src/interceptors/metrics.interceptor.ts#L86-L89

Strangely enough, I am not able able to reproduce this on my local machine any more 🤔

**Comment by bajtos** [comment]
The problem mentioned by my previous comment was caused by the fact that on Travis CI, we did not bootstrap all packages. I am assuming that as a result, typescript-eslint did not have access to dependencies and therefore it used incorrect typings. 

In 2e35a44, I have modified our Travis CI job to run a full bootstrap before calling eslint, this seems to fix the problem on my local machine.

**Pull request merged**
