### PR TITLE
remove empty table header from README.md

### PR DESCRIPTION
**Pull request by kerolloz**
in the project maintainers section  

I just turned markdown to HTML. because GitHub flavored markdown doesn't support tables without headers.  

I googled if there is any hack or workarounds to ignore the header in markdown but found nothing. please refer to this [stackoverflow](https://stackoverflow.com/a/17543474/9329261) answer for more.

### CODE REVIEW

**Comment by raymondfeng** [comment]
@kerolloz The README is rendered correctly on github. How did you run into the issue? What are you trying to achieve?

**Comment by kerolloz** [comment]
@raymondfeng 
The table of project maintainers has an empty table header. I was trying to remove it.
I'm using Mozilla Firefox(67.0.2) for Ubuntu .
Screenshot from 2019-06-20 01-41-00

**Comment by bajtos** [comment]
I like the proposed HTML version because I find it easier to read than the large Markdown table. It would be even better if each author could have a single `<td>` cell, but I am not sure how easy is that to achieve in HTML/CSS.

@kerolloz Please run `npm run lint:fix` to fix code formatting and also modify the commit message to follow our [Commit message guidelines](https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#commit-message-guidelines)

**Comment by kerolloz** [comment]
@bajtos 
please take a look at this [pull request](https://github.com/strongloop/loopback-next/pull/3211)

**Pull request closed without merging**
