### PR TITLE
[WIP] fix(docs): test verify-docs

### PR DESCRIPTION
**Pull request by dhmlau**
CI failed on `verify-docs` but it didn't happen locally. 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
I cannot reproduce it locally either.

**Comment by dhmlau** [comment]
@nabdelgadir suggested in https://github.com/strongloop/loopback-next/pull/4788#issuecomment-595811650 that the previous change in `href` might be causing the failure.
i.e.
```
<link rel="shortcut icon" type="image/x-icon" href="https://loopback.io/favicon.ico">
```

After changing everything back to `//loopback.io/..`, the failure didn't happen (surprisingly). I start to revert the changes back and CI still passes. 🤷‍♀  Will revert all the changes and see if it will pass again.

**Comment by dhmlau** [comment]
@raymondfeng, I might need your help on debugging this. Thanks! 

I have the following findings:
1. It seems like if a PR has changes in `docs/` folder, the `verify-docs` task will fail even I revert the changes in #4771. 
2. The error for `verify-docs` is:
```
lerna info Installing external dependencies
lerna ERR! npm ci exited 1 in '@loopback/extension-metrics'
lerna ERR! npm ci stderr:
npm ERR! cb() never called!
...
lerna ERR! npm ci exited 1 in '@loopback/extension-metrics'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
```
See full log in https://travis-ci.com/strongloop/loopback-next/jobs/295572539.
It didn't seem to be related to "verify-docs" and I didn't see any recent change in that package either.

**Comment by raymondfeng** [comment]
#4815 should fix the issue.

**Pull request closed without merging**
