### PR TITLE
docs: update @loopback/authentication readme file

### PR DESCRIPTION
**Pull request by emonddr**
Update @loopback/authentication package's README.MD

Related to : https://github.com/strongloop/loopback-next/issues/2940

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by emonddr** [comment]
At the bottom of the readme.md, there are two links:
- Authentication Component documentation (which has detailed coding examples)
- A tutorial on how JWT authentication was added to the shopping cart application (also with lots of coding examples).

I didn't see the need in providing coding examples in the readme.md file itself because this would be duplicating the same type of coding examples again.

This is why I chose to `point` to certain sections of the existing documentation for `coding examples`.

**Comment by emonddr** [comment]
The two documents mentioned have been committed to master branch, but as of yet, have not been released to loopback.io . 

@dhmlau , what would be the timeline for that? thx.

**Comment by dhmlau** [comment]
Per the conversation on Slack with @bajtos, we might want to check with @raymondfeng to see if the Build 2.0 task (https://github.com/strongloop/loopback-next/issues/3061) is done before we make a new release, because it will make a new semver-major for the build package.

**Comment by emonddr** [comment]
> Glad to see you've made it succinct

I made it succinct by pointing to the `detailed` document links! :)

**Pull request merged**
