### PR TITLE
chore(tslint): Add no-unused-variable to lint rules

### PR DESCRIPTION
**Pull request by kjdelisle**
### Description
Disallow unused variables and imports.

### CODE REVIEW

**Comment by kjdelisle** [comment]
Our lint config doesn't even follow the Prettify format, so now there's a ton of unrelated changes to the JSON...

**Comment by kjdelisle** [comment]
@bajtos After attempting to do this, I've noticed the linter is ignoring decorators being leveraged against classes, which means a ton of items get marked as violations even though they're valid.

I'm going to attempt this in an alternate PR using the compiler flag and then we can compare the results, as well as the pros/cons.

**Comment by kjdelisle** [comment]
An update: Many of the patterns we've established in repository.ts violate the compiler's noUnusedLocal rule:

```ts
// 'T' is declared but never used.
export class Repository<T extends Model> {} 

// 'ID' is declared but never used.
export class EntityRepository<T extends Entity, ID> extends Repository<T> {} 
```

The problem with this is that these interface definitions are still valuable even while performing no function directly. I don't think we can really enable a compile-time check on this, so I'll keep working on this version and see where it goes.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by bajtos** [comment]
@kjdelisle your comments make sense to me, thank you for capturing the rationale for choosing tslint option (vs. compiler option) for posterity 👍

**Pull request merged**
