### PR TITLE
fix the emitter

### PR DESCRIPTION
**Pull request by jannyHou**
## Description

`npm run build` fails on my local while passes on CI. Not sure is it my own problem, appreciate it if someone can test on their end.

```
> lb-tsc es2017 --outDir dist
npm WARN invalid config loglevel="notice"
benchmark/src/benchmark.ts(117,15): error TS2314: Generic type 'Emitter<EventName, EmittedType>' requires 2 type argument(s).
```

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
Did you have a different version of `@types/node`? Your PR causes CI to fail.

**Comment by raymondfeng** [comment]
@jannyHou I think you need to upgrade `p-event` to `^4.1.0` for all modules so that your PR can pass.

**Comment by jannyHou** [comment]
@raymondfeng 
> I think you need to upgrade p-event to ^4.1.0

👍 thanks!

**Comment by raymondfeng** [comment]
Actually, only `benchmark` has `p-event@^4.0.0`

**Comment by raymondfeng** [comment]
@jannyHou To be sure, your PR is valid but you need to upgrade `p-event` to `^4.1.0` in `benchmark/package.json`.

**Pull request merged**
