### PR TITLE
docs: fix link path to 'JWT Service'

### PR DESCRIPTION
**Pull request by ddsultan**
Fix broken link path to 'JWT Service' in 'Inside a LoopBack Application' section to improve developer (reading) experience  
 

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
Thanks for fixing the link.

**Comment by dhmlau** [comment]
@ddsultan, thanks for the PR. Could you please sign the DCO? You can do it by running the following command:
```
git commit --amend -s
```

Thanks.

**Comment by ddsultan** [comment]
> @ddsultan, thanks for the PR. Could you please sign the DCO? You can do it by running the following command:
> 
> ```
> git commit --amend -s
> ```
> 
> Thanks.

I thought signing a commit message with Github was enough.

I will make a new MR closing this one. The history looks a bit strange with the way I am doing it right now

**Comment by ddsultan** [comment]
Closing in favour of the new one to keep the history cleaner

**Pull request closed without merging**
