### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mediafreakch**
## Checklist
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated

### CODE REVIEW

**Comment by bajtos** [comment]
Hi @mediafreakch, thank for your the pull request. Before we can accept your first contribution, we need you to sign our CLA - see https://cla.strongloop.com/agreements/strongloop/loopback-next

Secondly, our CI build is failing for your changes.

1. Run `npm run lint:fix` to ensure all files are formatting according to our Prettier rules.
2. Fix your commit message to follow our [Commit message guidelines](https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#commit-message-guidelines)

Please make both changes in this pull request and keep a single git commit. If you are new to git, here are the commands to run:

```
# amend the last commit
# add more changes, edit the message
git commit --amend

# rewrite the branch on GitHub
git push --force-with-lease
```

**Comment by bajtos** [comment]
Hi @mediafreakch, what's the status of this pull request - are you still keen to finish it?

**Comment by mediafreakch** [comment]
It's a one-liner fix in docs. Take it or leave it. I didn't have time to go through the exhausting commit guidelines of this repo and I'm not very eager to do so.

**Comment by bajtos** [comment]
> I didn't have time to go through the exhausting commit guidelines of this repo and I'm not very eager to do so.

Understood, thank you for letting us know. We can fix the commit message for you, I see that @jannyHou has already done that.

**Comment by raymondfeng** [comment]
@jannyHou I don't see a fix of typo in the commit. It seems to be a new format that breaks CI. Should we close it?

**Comment by jannyHou** [comment]
@raymondfeng @bajtos Yeah I think it's already fixed. Closing the PR.

@mediafreakch Thank you for the contribution all the same! we appreciate your time and effort.

**Pull request closed without merging**
