### PR TITLE
Support multipart form data

### PR DESCRIPTION
**Pull request by goodexpert**
See https://github.com/strongloop/loopback-next/issues/1873

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by goodexpert** [comment]
I'd like to add an uploading file feature for @loopback-next framework.

**Comment by bajtos** [comment]
Hi @goodexpert, thank you for the contribution, this is a great start! IIUC, you are building on top of  https://github.com/strongloop/loopback-next/pull/1838, thus we will need to land that pull request first, right?

Please sign our Contributor License Agreement, we cannot accept your contribution without that. See https://cla.strongloop.com/agreements/strongloop/loopback-next

Secondly, we will need you to add automated tests to cover your new feature. I would like to see at least one acceptance test showing how to write a controller method accepting file uploads.

Last but not least, the Travis CI build is failing in [code-lint](https://travis-ci.org/strongloop/loopback-next/jobs/443593461) and [commit-lint](https://travis-ci.org/strongloop/loopback-next/jobs/443593461) steps. You can fix most linting errors by running `npm run lint:fix`. To change the commit message, run `git rebase -i master`, select `reword` action for the commits needed changes and after the rebase is done, rewrite the history on GitHub by running `git push --force-with-lease`.

I highly recommend you to read our [DEVELOPING guide](https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md) to better understand our conventions.

**Comment by goodexpert** [comment]
I have fixed some of issue and added an unit testing of  multipart/form-data

**Comment by bajtos** [comment]
@goodexpert thank you for the updates. As I see it, adding support for file uploads is a big feature that will live with us for many months or years and will be difficult to significantly change. I'd like us to carefully design this figure in a way that will be robust, secure and extensible to support future needs. Let's discuss these high-level topics in #1873 first please, before looking at implementation details.

**Comment by kawasaki23Ven** [comment]
Is this available?

**Comment by goodexpert** [comment]
> Is this available?

Yes, I have applied this to my project to upload files with form data.

**Comment by goodexpert** [comment]
Please check my new pull request.

**Comment by bajtos** [comment]
Closing in favor of https://github.com/strongloop/loopback-next/pull/1989

**Pull request closed without merging**
