### PR TITLE
paramTypes does not always exist

### PR DESCRIPTION
**Pull request by SephReed**
Adding this condition, made the following code example work.

```
import {ApplicationConfig} from '@loopback/core';
import {RestApplication, RestServer, get, param} from '@loopback/rest';


export class HelloController {
  @get('/hello/{name}')
  hello(@param.path.string('name') name: string): string {
    return `hello ${name}`;
  }
}

export class HelloWorldApplication extends RestApplication {
  constructor(options: ApplicationConfig = {}) {
    super(options);

    this.controller(HelloController);
  }

  async start() {
    await super.start();
    const rest = await this.getServer(RestServer);
    console.log(
      `REST server running on localhost:${await rest.get('rest.port')}`,
    );
  }
}
```

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@SephReed Thank you for the patch. Please follow instructions at https://loopback.io/doc/en/lb4/submitting_a_pr.html to fix a few things:

1. Sign CLA - https://cla.strongloop.com/agreements/strongloop/loopback-next
2. Change the commit message to be somethings like `fix(openapi-v3): allows paramTypes to be undefined`
3. Add a test case to cover the example you illustrate in the PR.

**Comment by SephReed** [comment]
You hereby have my permission to use the shared code in any manner whatsoever, including taking credit or ownership for it.

@raymondfeng Jumping through all the hoops to get this fix in is a pretty big investment.  Could you guys find a way to include this without me doing all that?

**Comment by raymondfeng** [comment]
@SephReed The conventions are enforced to ensure the consistency of our code base for better maintainability.  We respect your decision to give us the permission to take over.

BTW, I tried your example application with latest LoopBack 4. It works out of box without your proposed change.

**Comment by raymondfeng** [comment]
For the record, the transplied JS code should have a snippet as follows:

```js
__decorate([
    rest_1.get('/hello/{name}'),
    __param(0, rest_1.param.path.string('name')),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [String]),
    __metadata("design:returntype", String)
], HelloController.prototype, "hello", null);
```

This should return `[String]` for paramTypes.

**Pull request closed without merging**
