### PR TITLE
docs: remove calling other apis page

### PR DESCRIPTION
**Pull request by virkt25**
connected to #988 
Copy of https://github.com/strongloop/loopback.io/pull/641 since docs were migrated before that PR landed. 

The entire page is a big To Do as the features haven't been implemented yet. I am proposing removing this page TILL these features are implemented at which point the docs have to be written anyways. 

RATIONALE: There is no content worth keeping and as a user when I click the page I would expect to find information on how to accomplish what the title states instead of finding a page saying it's a feature to be added to the framework.

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

**Comment by virkt25** [comment]
There's only 3 bullets on the page. I think that's the obvious sections someone will write as they work on the docs after this feature is implemented.

**Comment by raymondfeng** [comment]
Maybe keeping the pages and adding a disclaimer to state such feature is to be implemented makes sense in this case for two reasons:

1. The feature is coming soon
2. We can avoid questions for those who already know LB3 can interact with REST/SOAP/... and wonder if LB4 does so or not

I won't block the PR if majority of us think it's better to remove.

**Comment by virkt25** [comment]
User can see features we have planned via WIP PR's and Issues. I don't think Docs is the place to show it but that said I'm not against keeping the page. 

@raymondfeng Do you think the current notice on the page is sufficient? 

`Work-in-progress: This section is not yet complete.`

**Comment by bajtos** [comment]
I slightly prefer Raymond's proposal to keep the page with the current TODO notice, but don't mind to remove the page either.

**Comment by virkt25** [comment]
Closing this PR as the page has a notice that this is a feature that is coming soon.

**Pull request closed without merging**
