### PR TITLE
docs: remove language-related-concepts.md

### PR DESCRIPTION
**Pull request by shimks**
The replacement of content being deleted here is tracked by these issues:
- #673 
- #1149 

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] Related API Documentation was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

**Comment by virkt25** [comment]
As much as I want to see these pages gone, I think it might be better to wait till this content is migrated into a more appropriate doc. 

Maybe for the short term it's better to move this under concepts and update the page to say that this is a language related concept but is a pattern used by LoopBack 4.

**Comment by shimks** [comment]
I may have jumped the gun here with deleting the page. As @virkt25 said, I'd be ok with just migrating `mixin.md` to key concepts and then deleting `language-related-concepts.md`

**Comment by shimks** [comment]
Actually, I want to take back what I said. Having taken a look at `mixin.md`, the code examples it uses make no intuitive sense in context to the framework, and I feel it's better to get rid of the page then it is to mislead users with codes with no practical application.

**Comment by b-admike** [comment]
I think we could revamp this page to make it relevant to the framework. We can remove it from the sidebar, and leave the page as is until we revisit it. Then again, users can still see it, so perhaps having it in git history and tracked in an issue so we can fix it is good enough.

**Comment by shimks** [comment]
@slnode test please

**Pull request merged**
