### PR TITLE
[WIP] feat: add access token UI

### PR DESCRIPTION
**Pull request by hacksparrow**
Add UI for specifying the access token in API Explorer. Also makes additional UI improvements.

**Old**
image

**New**
image

### CODE REVIEW

**Comment by bajtos** [comment]
I am confused. How do you envision to use the access token set in the UI? In your pull request, I don't see how the value is passed to the underlying swagger-ui or swagger-js implementation. 

Also note that by default, LoopBack 4 applications don't have authentication enabled, they don't accept any access tokens!

**Comment by bajtos** [comment]
IMO, we need to implement first few parts of Authentication epic https://github.com/strongloop/loopback-next/issues/1035, most notably https://github.com/strongloop/loopback-next/issues/1997, before it makes sense to work on API Explorer enablement.

**Comment by hacksparrow** [comment]
> I don't see how the value is passed to the underlying swagger-ui or swagger-js implementation.

Work in progress.

After discussing with you on Slack, looks like this is indeed early.

**Comment by sbacem** [comment]
I think is better to use like this in SwaggerUI

capture
 
and 

capture2

**Comment by bajtos** [comment]
> I think is better to use like this in SwaggerUI

+1 to use swagger-ui's built-in controls and don't reinvent the wheel.

**Comment by hacksparrow** [comment]
@sbacem is that an in-built feature in SwaggerUI? How do you bring it up?

**Comment by sbacem** [comment]
@hacksparrow you can see this [https://editor.swagger.io](https://editor.swagger.io/?_ga=2.136414640.1865821691.1546850370-1844356384.1546850370)

In first step is to define your security strategy

```
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
```
After this  you can use this definition in path like this 
```
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

```

**Comment by bajtos** [comment]
Thank you @sbacem for an example of how to configure auth/auth in OpenAPI. The full spec can be found here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#securitySchemeObject

Here are the valid auth types: "apiKey", "http", "oauth2", "openIdConnect". We have been using "apiKey" type in LoopBack 3.x, I think that's the direction we are investigating for LB4 too.

cc @jannyHou

**Comment by hacksparrow** [comment]
Thanks @sbacem!

**Comment by raymondfeng** [comment]
As we improve the authentication/authorization support, security related metadata should be generated into the OpenAPI spec.

**Comment by hacksparrow** [comment]
Closing this as we won't need to work on additional UI.

**Comment by shendkardevesh** [comment]
hi , confuse how to get ui changed for accepting authentication key

**Comment by dougal83** [comment]
@shendkardevesh The UI is not ready yet, for implementation progress see issue: https://github.com/strongloop/loopback-next/issues/2027 

You can use a tool like [Postman](https://www.getpostman.com/) to query the API with an access token in the meantime.

**Pull request closed without merging**
