### PR TITLE
Disable node v16 temporality

### PR DESCRIPTION
**Pull request by frbuceta**
## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@frbuceta Do we know why CI fails for Node 16?

**Comment by frbuceta** [comment]
> @frbuceta Do we know why CI fails for Node 16?

It seems that the command npm test of the acceptance tests of the cli does not work but it only does not work in GitHub Actions because in local it does.

And in GitHub Actions the error is not printed and I do not know if it is a Mocha or Github problem

**Comment by datpp** [comment]
@frbuceta image I saw this error, but have no idea how to fix now.

**Comment by frbuceta** [comment]
> @frbuceta image I saw this error, but have no idea how to fix now.
> 
> cc @raymondfeng

Only fails when using NPM v7

**Comment by frbuceta** [comment]
Close in favor of #7520

**Comment by raymondfeng** [comment]
@datpp Great troubleshooting. It's surprising that we cannot reproduce it locally. There must be something strange going on github actions.

**Pull request closed without merging**
