### PR TITLE
fix(cli): updated OAS 'date' type mapping to JS 'string'

### LINKED ISSUE #4085: OpenAPI 'date' is always 'date-time'
## Steps to reproduce

Generate models using openapi where the format is 'date'. Try and pass a date value '2019-01-01' to the server.

## Current Behavior

The server returns 422 unprocessable entity because the date doesn't match the 'date-time' format.

## Expected Behavior

It should parse the date only format.

## Additional information

This is caused by the line here:

https://github.com/strongloop/loopback-next/blob/cd5ca92c368ae35bc10d8847b3b0d379f7196544/packages/repository-json-schema/src/build-schema.ts#L234

The models themselves don't get a decorator attached to indicate the type of format, so at this point it's not possible to infer whether it's a date or a date-time.

```
"@loopback/boot": "^1.5.10"
"@loopback/context": "^1.23.4"
"@loopback/core": "^1.10.6"
"@loopback/openapi-v3": "^1.10.0"
"@loopback/rest": "^1.22.0"
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by achrinza**
Fixes #4085

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@achrinza Please squash the commits into one per https://loopback.io/doc/en/lb4/submitting_a_pr.html

**Comment by achrinza** [comment]
@raymondfeng Sorry about that, it's been squashed

**Comment by achrinza** [comment]
@raymondfeng It's been squashed

**Comment by dhmlau** [comment]
In case you're interested, there is a LoopBack Developer badge for those who made contributions to LoopBack. Please check this out:  https://www.ibm.com/services/learning/ites.wss/zz-en?pageType=badges&id=0de05804-8037-4791-ac83-09829b566d51. Thanks!

**Comment by achrinza** [comment]
Thanks @dhlmanu; how can it be claimed?

**Pull request merged**
