### PR TITLE
chore: update Mixin.md

### PR DESCRIPTION
**Pull request by odykyi**
chore: update Mixin.md

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by nabdelgadir** [comment]
> @odykyi, thanks for the PR.
> The `verify-docs` check failed in CI, i'm kicking it off again.

@dhmlau I restarted it again and it's still failing, which is weird.

**Comment by achrinza** [comment]
#4786 also seems to be experiencing a similar issue - rebasing didn't resolve the issue

**Comment by nabdelgadir** [comment]
> #4786 also seems to be experiencing a similar issue - rebasing didn't resolve the issue

@dhmlau do you think a new PR should be created for this?

**Comment by dhmlau** [comment]
@nabdelgadir, did you have a chance to run locally on the verify-docs? 
Given the changes are minor, I think it's ok to force merge it after fixing the commit message. 
But I guess we probably need to find out why it's happening, because it seems like it's not the only incident (see @achrinza's comment: https://github.com/strongloop/loopback-next/pull/4788#issuecomment-595248642).

**Comment by achrinza** [comment]
> 
> 
> > #4786 also seems to be experiencing a similar issue - rebasing didn't resolve the issue
> 
> @dhmlau do you think a new PR should be created for this?

Unfortunately #4802 is still experiencing the same issue :/

**Comment by nabdelgadir** [comment]
> @nabdelgadir, did you have a chance to run locally on the verify-docs?
> Given the changes are minor, I think it's ok to force merge it after fixing the commit message.

Yeah, `verify:docs` works locally and `build:site` does too! I previewed the changes on the loopback.io repo (because I have some issues with the sandbox version) and it works too. 

> But I guess we probably need to find out why it's happening, because it seems like it's not the only incident (see @achrinza's comment: [#4788 (comment)](https://github.com/strongloop/loopback-next/pull/4788#issuecomment-595248642)).

From these two instances, it seems to be happening only on docs PRs from forked repos (your PR https://github.com/strongloop/loopback-next/pull/4771 didn't have this issue) or it might be a problem that started happening some time after you landed your PR. Should we open an issue to investigate?

**Comment by dhmlau** [comment]
@nabdelgadir, thanks. Let me open a test docs PR and see.

**Comment by raymondfeng** [comment]
The build failure is fixed by #4815.

**Pull request merged**
