### PR TITLE
[DO NOT MERGE] Proposed spikes for JSLB4

### PR DESCRIPTION
**Pull request by hacksparrow**
As suggested by @bajtos - https://github.com/strongloop/loopback-next/issues/1978#issuecomment-463960626.

### CODE REVIEW

**Comment by dhmlau** [comment]
Capturing my comments in [here](https://github.com/strongloop/loopback-next/issues/1978#issuecomment-463901205).

My thought process is:
1. Based on what we know about the JS experience, can we create a tutorial to let our users know how it can be done?   It doesn't need to be the perfect DX but at least we can show them a way.  Or we should do some enhancements before the tutorial?
2. If there's some enhancement needs to be done, what would be the MVP?

**Comment by raymondfeng** [comment]
@hacksparrow Why don't we use a github issue or wiki instead of PR to discuss the spike?

**Comment by hacksparrow** [comment]
@raymondfeng @bajtos suggested to create a markdown file and commit it.

**Comment by bajtos** [comment]
The spike has been already finished, this PR is no longer relevant.

**Pull request closed without merging**
