### PR TITLE
Update todo-tutorial-model.md

### PR DESCRIPTION
**Pull request by mlaopane**
Typo in the console output after interactive model creation.

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by dhmlau** [comment]
@mlaopane , thanks for the PR.  Could you please sign the CLA? Thanks! https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by mlaopane** [comment]
It looks like I can't (504 error).

Feel free to make the fix yourself and reject the PR.

**Comment by bajtos** [comment]
The CLA shows as signed now.

The CI build is failing in the commit-lint step, see https://travis-ci.org/strongloop/loopback-next/jobs/462223262#L450

```
⧗   input: 
Update todo-tutorial-model.md
Typo in the console output after interactive model creation.
✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
```

@mlaopane could you please fix the commit message to follow our conventions? See https://loopback.io/doc/en/contrib/code-contrib-lb4.html#commit-message-guidelines

If you are not familiar with git history rewriting yet:

```shell
$ git commit --amend
# edit the message
$ git push --force-with-lease
```

While you are at making these changes, please rebase your patch on top of the latest master. Quoting from https://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request:

> Our code base is always getting updated and being able to successfully rebase your PR is very important. Here are some simple steps to rebase your code:
> - Checkout your branch which you are submitting the pull request against `git checkout <my_branch>`
> - Add an upstream remote from your fork `git remote add upstream <upstream_repo>`
> - Fetch the latest from the **_upstream_** remote `git fetch upstream`
> - Rebase your code using the interactive mode `git rebase -i upstream/master`
> - If you are happy with the changes and there are no merge conflicts, push the code to your remote branch `git push --force-with-lease origin <my_branch>`

**Comment by dhmlau** [comment]
@mlaopane, thanks for your contribution.  I've rebased and fixed the commit message.  Your PR has landed. 🎉

**Pull request merged**
