### PR TITLE
fix: fix cli rest controller generator template

### LINKED ISSUE #1551: Controller CLI generator produces invalid `updateAll` route
Current CRUD controller generator produces invalid code

## Description / Steps to reproduce / Feature proposal
1. Generate a new app
2. Generate a new model
3. Create a new repository
4. Generate a new controller using `lb4 controller`
5. Select REST Controller with CRUD Functions
6. Select the model and repository previously created

## Current Behavior
A new controller will be generated with a missing comma at the end of line 38 and a line-ending comma that fails lint at the end of line 39

## Expected Behavior
Line 38 ends in a comma, and line 39 has no trailing comma

### PR DESCRIPTION
**Pull request by steevsachs**
Fix commas on lines 38 and 39 of `packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs` to produce valid code that passes lint

Fixes #1551

### CODE REVIEW

**Comment by marioestradarosa** [comment]
Relates to #1535

**Comment by shimks** [comment]
@steevsachs I've rebased your branch for you so that this issue can land ASAP. I've also added co-authorship from @marioestradarosa, whose PR came first.

**Comment by steevsachs** [comment]
@shimks Thank you for that. Apologies for not finding the other PR / issue prior to submission.

**Comment by shimks** [comment]
@steevsachs No worries, the previous PR should've been landed sooner than it did.

The PR has been landed 🎉 . Thanks for the contribution @steevsachs!

**Pull request merged**
