### PR TITLE
fix(docs): documentation code snippet missing imports

### LINKED ISSUE #3581: show imports in documentation
Sorry if this is incorrect template/repo for this suggestion.

## Steps to reproduce

When reading the docs on [https://loopback.io/doc/en/lb4/](https://loopback.io/doc/en/lb4/) for any of the Getting started tutorials.

## Current Behavior

It is most often problematic as a new into LB4 to know where the imports are made from with all the new syntax/concepts.
One specific example is [https://loopback.io/doc/en/lb4/Interceptors.html#apply-interceptors](https://loopback.io/doc/en/lb4/Interceptors.html#apply-interceptors)

## Expected Behavior

It would be very convenient if the code snippets "always" shows from where different imports that is needed from the `@loopback/{any}`-packages.

## Link to reproduction sandbox
example:
```ts
import {intercept} from '@loopback/core'; 
// ^-- Add these lines so that newcomers can start learning the concepts.

class MyController {
  @intercept(log) // Use the `log` function
  greet(name: string) {
    return `Hello, ${name}`;
  }
}
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

---

## 🎆 Hacktoberfest  2020

Greetings :wave: to all Hacktoberfest 2020 participants!

Here are few tips 👀 to make your start easier, see also #6456.

- Before you start working on this issue, please leave a comment to let others know.
- We don't have a full list of code snippets that are missing `import` statements, we rely on you to find the places needing improvement. Don't worry if you miss some, others will pick them up later. It's perfectly fine to work in small steps, changing only few pages in a single pull request. Baby steps FTW, every little helps!
- If you are new to GitHub pull requests, then you can learn about the process in [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).
- If this is your first contribution to LoopBack documentation, then read [Documentation guide for LoopBack 4 developers](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#documentation) please. Consider [previewing loopback-next docs only](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#previewing-loopback-next-docs-only) for a faster feedback loop. Finally, please refer to [Contributing to LoopBack documentation](https://loopback.io/doc/en/contrib/doc-contrib.html) for a more advanced information on our Jekyll-based documentation infrastructure.
- Feel free to ask for help in `#loopback-contributors` channel, you can join our Slack workspace [here](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw).

### PR DESCRIPTION
**Pull request by pktippa**
Signed-off-by: Pradeep Kumar Tippa <pktippa@gmail.com>

Fixes #3581 

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]

**Review by nabdelgadir — APPROVED** [review]

**Comment by nabdelgadir** [comment]
@pktippa Do you know if these are these the only outdated/missing imports? Just wondering so we know if we can close the main issue.

Thanks for the PR either way!

**Comment by pktippa** [comment]
@nabdelgadir I haven't verified the entire documentation, let me know how to proceed further.

**Comment by nabdelgadir** [comment]
@pktippa I don't think it's worth going through the whole documentation, honestly. I see @dhmlau already closed the issue, so we can leave it as is for now. Thanks for your help!

**Comment by pktippa** [comment]
Thanks, glad to contribute.

**Comment by dhmlau** [comment]
@nabdelgadir, I think it closes because the original comment in this PR has `Fixes <issue #>`. :). But I agree that it would be better to fix/open a new issue if there are particular missing imports we found.

**Pull request merged**
