### PR TITLE
docs: todo tutorial documenation fix

### PR DESCRIPTION
**Pull request by pktippa**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by bajtos** [comment]
Thank you @pktippa for the pull request. 

The changes look good to me, now we need you to make the CI build pass. 

https://travis-ci.com/strongloop/loopback-next/jobs/241756109
```
> loopback-next@0.1.0 prettier:cli /home/travis/build/strongloop/loopback-next
> node packages/build/bin/run-prettier "**/*.ts" "**/*.js" "**/*.md" "-l"

docs/site/tutorials/todo/todo-tutorial-scaffolding.md
```

You can run `npm run lint:fix` to resolve.

https://travis-ci.com/strongloop/loopback-next/jobs/241756110

```
$ commitlint-travis
⧗   input: TODO tutorial documenation fix
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

See our [Commit Message Guidelines](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines), you can run `git commit --amend` to fix the commit message.

Then run `git push --force-with-lease` to overwrite git history on GitHub remote too.

**Comment by pktippa** [comment]
@bajtos Okay, the builds are failing because of commit message is not in proper format ?

**Comment by pktippa** [comment]
@bajtos fixed linting issues on commit messages.

**Comment by jannyHou** [comment]
@pktippa Thank you for the contribution, based on Miroslav's comment, can you run `npm run lint:fix` again to fix the lint errors in the markdown file? 
We can help you land the PR after CI pass.

**Comment by pktippa** [comment]
@jannyHou ran lint:fix, now have to see the CI build. thanks.

**Comment by dhmlau** [comment]
@pktippa, thanks for your contribution.  Your PR has landed! 🎉

**Pull request merged**
