### PR TITLE
docs: fixes typo in 'Authentication-overview.md'

### PR DESCRIPTION
**Pull request by alma3lol**
## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@alma3lol, thanks for catching that. Could you please sign off the commit by running:
```
git commit --amend -s
```
Thanks.

See https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco for details.

**Comment by alma3lol** [comment]
@dhmlau Working on it.

**Comment by alma3lol** [comment]
@dhmlau done

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@alma3lol, thanks again for your contribution. Your PR has landed. 🎉

**Pull request merged**
