### PR TITLE
feat: add an example for multi-tenancy

### PR DESCRIPTION
**Pull request by raymondfeng**
See #5056 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by hacksparrow** [comment]
> We simply rebind `datasources.db` to a tenant specific datasource to select the
right datasource for `UserRepository`.

@raymondfeng  So, if I understand correctly, multitenancy is achieved by switching the datasource to the configured for the tenant.

At what point is the switch done? As soon as a request arrives? What if there is a long running query for a tenant and a new request arrives for another one? What if there was some code to be executed after query was a successful; is it guaranteed that this code will not be executed for another tenant?

**Comment by raymondfeng** [comment]
> @raymondfeng So, if I understand correctly, multitenancy is achieved by switching the datasource to the one configured for the tenant.

> At what point is the switch done? As soon as a request arrives? What if there is a long running query for a tenant and a new request arrives for another one? What if there was some code to be executed after query was a successful; is it guaranteed that this code will not be executed for another tenant?

Please note that we create a new `RequestContext` per request. The switch happens at per request level. The req/res processing is fully isolated from each other with our dependency injections for stateful artifacts.

**Comment by hacksparrow** [comment]
Yes, there's a new `RequestContext` per request, however, `datasources.db` is shared by all, isn't it?

@bajtos thoughts?

**Comment by raymondfeng** [comment]
> Yes, there's a new RequestContext per request, however, datasources.db is shared by all, isn't it?

`datasources.db` by default a singleton with connection pool to the backend DB. It's bound at application level by `app.boot`. We are rebinding it to a new alias at `RequestContext` level so that there is a tenant specific DS for the given request.

```
request 1 with tenant `abc`:
abc: Request context (datasources.db -> datasources.db.abc: DB for abc)
         Application (datasources.db -> default DB)

request 2 with tenant `xyz`:
xyz: Request context (datasources.db -> datasources.db.xyz: DB for xyz)
         Application (datasources.db -> default DB)
```

**Comment by Dainiu5** [comment]
Hi, great stuff! :+1:
From my understanding, in this current implementation one can switch between pre-defined data sources based on the tenant id. However, what could be done to switch between database schemas using a specific postgres datasource?
Any hint or suggestions how it could be done would be highly appreciated. 
Thanks!

**Pull request merged**
