### PR TITLE
chore: update copyright headers for repository*, rest*, service-proxy and testlab packages

### PR DESCRIPTION
**Pull request by dhmlau**
Update copyright headers for the following packages:
- repository
- repository-json-schema
- rest
- rest-explorer
- service-proxy
- testlab

The changes in this PR are generated by running slt copyright in each package.

FYI - the copyright year is in the format of <year1, year2>, where year1 is the year that the file was created, year2 is the year that the file was last touched.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by raymondfeng** [comment]
@dhmlau I wonder why you created multiple PRs for the changes. It should be done in one PR avoid overheads as it's automatically generated by a tool.

We should also set up the tool as a script so that we can run it periodically (maybe part of the release process).

**Comment by dhmlau** [comment]
@raymondfeng, yes, I could've.  I was thinking breaking it down into a few PRs would make the reviews easier. :)  Will remember that next time. 

I used `git-walk` https://www.npmjs.com/package/git-walk for running the copyright statements updates in the past, it goes to all the repos in the given folder and applies the same command.  Perhaps if we're going to automate this, we can use that.

**Comment by dhmlau** [comment]
@bajtos had suggested to push directly to master, but I'd prefer to do it in a PR just in case...

**Comment by raymondfeng** [comment]
> I used git-walk https://www.npmjs.com/package/git-walk for running the copyright statements updates in the past, it goes to all the repos in the given folder and applies the same command. Perhaps if we're going to automate this, we can use that.

So `slt copyright` does not handle multiple files in folders?

**Comment by dhmlau** [comment]
> So slt copyright does not handle multiple files in folders?
IIUC, it doesn't. that's why we need git-walk.

**Pull request merged**
