### PR TITLE
[WIP RFC] docs: add a draft of extensibility UX

### PR DESCRIPTION
**Pull request by raymondfeng**
## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by bajtos** [comment]
I'll take a look later, hopefully by the next week.

**Comment by raymondfeng** [comment]
> I'll take a look later, hopefully by the next week.

Thanks. Just to warn you that the PR is probably premature at the moment. I'm dumping thoughts without organizing them and it will take some time to make it readable :-).

**Comment by bajtos** [comment]
> Just to warn you that the PR is probably premature at the moment. I'm dumping thoughts without organizing them and it will take some time to make it readable :-).

Ah, good to know! When I received a notification from GitHub, I thought this is something to review. I'll wait until the text is more shaped, please let me know when it's ready.

**Comment by raymondfeng** [comment]
With the introduction of `@inject.*` that allows BindingFilter and `@config.*` for configuration, I think we have a pretty good extensibility story now, which is reasonably documented.

**Pull request closed without merging**
