### PR TITLE
docs: updating links for jwt-authentication documentation

### PR DESCRIPTION
**Pull request by hectorleiva**
Signed-off-by: Hector Leiva <hector@hectorleiva.com>

There were some links in the migration documentation from Loopback 3 to Loopback 4 that were pointing to files that had moved. This PR is intended to point to the files where they currently reside now to avoid 404's for future users.

## Checklist

- [X] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [X] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
@hectorleiva, thanks for catching that.

**Comment by dhmlau** [comment]
Just realized there's CI failure due to code linting error. Could you please run `npm run lint:fix` and see if it fixes the problem? Thanks.

**Comment by dhmlau** [comment]
I'll "un-approve" for now to make sure we get the code linting error addressed. Thanks.

**Comment by hectorleiva** [comment]
Ah my bad. I went ahead and ran `npm run lint:fix` and I `git push -f` to update the commit. I ran `npm test` locally to be sure as well and it seems that everything is passing as expected now.

Thanks for your patience!

**Review by achrinza — APPROVED** [review]

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@hectorleiva, thanks for your contribution. Your PR has landed! 🎉

**Pull request merged**
