### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by jannyHou**
Signed-off-by: jannyHou <juehou@ca.ibm.com>

The project maintainers is in disorder in https://github.com/strongloop/loopback-next#project-maintainers
vscode preview looks good but the website doesn't, so I regarated the table with https://www.tablesgenerator.com

Click the new file and preview it on website: 
Screen Shot 2020-11-26 at 9 59 37 AM

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by nabdelgadir — APPROVED** [review]
Minor nitpick but would it be possible to centre the icons like it was before? If not, then LGTM. 👍

**Review by dhmlau — APPROVED** [review]
@jannyHou, thanks for taking care of that!

**Comment by jannyHou** [comment]
@nabdelgadir good catch! Fixed

**Comment by jannyHou** [comment]
Screen Shot 2020-11-26 at 11 13 05 AM

**Pull request merged**
