### PR TITLE
fix(rest): a small typo fix in code comments

### PR DESCRIPTION
**Pull request by pktippa-bn**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by raymondfeng** [comment]
@pktippa-bn Please fix the [commit message](https://travis-ci.org/strongloop/loopback-next/jobs/515282408) per instructions at https://loopback.io/doc/en/lb4/submitting_a_pr.html#1-commits-to-local-repository

**Comment by dhmlau** [comment]
@pktippa-bn , could you please address @raymondfeng's comment [above](https://github.com/strongloop/loopback-next/pull/2683#issuecomment-479586003)?  The linting error is: 
```
⧗   input: fixed errors in todo tutorial controller
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings 
    (Need help? -> https://github.com/conventional-changelog/commitlint#what-is-commitlint )
```
Thanks.

**Comment by dhmlau** [comment]
@nabdelgadir, could you please help land this PR? Thanks!

**Comment by pktippa** [comment]
Sure

**Comment by nabdelgadir** [comment]
@pktippa let me know if you need any help with changing the commit message or rebasing, so we can land this. Here's the format we use: https://loopback.io/doc/en/contrib/code-contrib-lb4.html#commit-message-guidelines.

**Comment by pktippa** [comment]
@nabdelgadir @raymondfeng  The issue is because of some old commit already there in the git repo.


`$ git log --grep='todo tutorial controller'                                                                                                                                  

commit f8f76d8959391d96699c412083acbdd0a9cf2426                                                                                                                              
Author: Csaba Kiss                                                                                                                                         
Date:   Mon Oct 1 22:24:28 2018 -0600                                                                                                                                                                                                                                                                                                                         
fixed errors in todo tutorial controller`

Tried to fix the commit message by myself by following this https://stackoverflow.com/questions/38892599/change-commit-message-for-specific-commit

but thought its not a good idea. Please help here.

**Comment by dhmlau** [comment]
@pktippa-bn , have you tried `git commit --amend`? https://help.github.com/en/articles/changing-a-commit-message

**Comment by bajtos** [comment]
@pktippa-bn I think the root cause of the problem is that you started your pull request from the `master` branch and did not create a feature branch. I'll try to clean up the git history for you now.

**Comment by bajtos** [comment]
Closing in favor of https://github.com/strongloop/loopback-next/pull/2705

**Pull request closed without merging**
