### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by virkt25**
## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

**Comment by shimks** [comment]
What's the dependency upgrade for? Does it have to do with yesterday's brief issue with `util` and `promisify`?

**Comment by virkt25** [comment]
Nope, this is completely unrelated to the `util/promisify` issue. I still have no idea what caused that. I had to update the deps in `@loopback/authentication` so I figured I might as well check all other packages as well. Didn't think it made sense to update the deps in that PR so made a new one.

**Comment by shimks** [comment]
In that case, is it necessary to update these dependencies if the current versions work fine?

**Comment by b-admike** [comment]
@shimks IMO it's good practice to keep deps up to date.

**Comment by virkt25** [comment]
These are also just minor / patch releases so it's what CI picks up anyways. The update just sets it explicitly to be the minimum version

**Pull request merged**
