### PR TITLE
docs: fix controllers readme url in parsing-requests.md page

### PR DESCRIPTION
**Pull request by labidiaymen**
Update a 404 link in the docs 
Page Parsing-requests.md

### CODE REVIEW

**Comment by raymondfeng** [comment]
@labidiaymen Thank you for the patch. Please sign [CLA](https://cla.strongloop.com/agreements/strongloop/loopback-next).

**Comment by raymondfeng** [comment]
Please also amend the commit message to be something like `docs: fix controllers readme url`

**Comment by labidiaymen** [comment]
Thanks for your reply

- CLA singed
- Commit message updated

**Comment by raymondfeng** [comment]
@labidiaymen You have to use `git commit --amend` command to fix the commit message, not the title of this PR.

Please also rebase against `master` to ensure CI is passing.

**Comment by labidiaymen** [comment]
Closing this pull request for a clean one https://github.com/strongloop/loopback-next/pull/2278

**Comment by raymondfeng** [comment]
FYI: You don't have to close this PR to get a clean one. Usually you can rebase it against master and force push back to your branch. Please note the PR will always pick up the latest changes from the source branch.

**Pull request closed without merging**
