### PR TITLE
Use the LTS version of Node in the dockerfile

### PR DESCRIPTION
**Pull request by frbuceta**
## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]

**Review by achrinza — APPROVED** [review]

**Comment by frbuceta** [comment]
> Sorry for the re-review;
> 
> We should consider explicitly defining the Node.js version, otherwise it may be ambiguous (e.g. private container image registry)
> 
> Renovate Bot seems to have built-in support to update Dockerfiles, let's see if we can leverage that instead:
> 
> #7577

I'm going to see if I can configure renovate to only update to LTS. Version 16 is not LTS yet

**Comment by dhmlau** [comment]
actually i just landed a PR from renovatebot from loopback4-example-shopping repo https://github.com/strongloop/loopback4-example-shopping/commit/49feb15955698f055a27e728b3b734adc9ee7cb6.

**Comment by Rungrot19** [comment]
> ## Checklist
> * [x]  DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
> * [x]  `npm test` passes on your machine
> * New tests added or existing tests modified to cover all changes
> * [x]  Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
> * API Documentation in code was updated
> * Documentation in [/docs/site](../tree/master/docs/site) was updated
> * Affected artifact templates in  were updated`packages/cli`
> * Affected example projects in  were updated`examples/*`
> 
> 👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

**Comment by dhmlau** [comment]
@frbuceta, since PR https://github.com/strongloop/loopback-next/pull/7577 (from RenovateBot) covers packages that are not covered in this PR. so I've landed #7577. WIth that, we no longer need this PR. Thanks for initiating this effort.

**Pull request closed without merging**
