### PR TITLE
Cleanup GitHub Actions workflows

### PR DESCRIPTION
**Pull request by achrinza**
Did a casual regression test on the commit lint using a deliberately bad commit - Looks like it still works fine with the new code and is able to catch bad commit bodies. (see [reference run](https://github.com/strongloop/loopback-next/pull/6997/checks?check_run_id=1672437843)):

```
⧗   input: Merge b0e774226ad14a0183411d21f442d459797dbdce into f91a7eed1219650e1bedffe8b9445f3c943bfb6d
✔   found 0 problems, 0 warnings
⧗   input: This is a deliberately bad commit
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

⧗   input: ci: remove unecessary steps from ci
✔   found 0 problems, 0 warnings
⧗   input: ci: remove unecessary steps from codeql analysis
✔   found 0 problems, 0 warnings
Error: Process completed with exit code 1.
```

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by raymondfeng — APPROVED** [review]

**Review by mrmodise — COMMENTED** [review]
@achrinza maybe add timeouts?

```
 name: Test
    timeout-minutes: 60
    strategy:
```

**Comment by achrinza** [comment]
@mrmodise The tests average ~10 mins. Hence I've set the timeout to 15 mins. WDYT?

**Comment by mrmodise** [comment]
> @mrmodise The tests average ~10 mins. Hence I've set the timeout to 15 mins. WDYT?

I meant per phase in case anything goes wrong to avoid pipeline running indefinitely. Use case could be when one submits a pipeline that breaks the CI process. 60 minutes was just a suggestion we can limit it to whatever is applicable

**Review by mrmodise — APPROVED** [review]

**Comment by achrinza** [comment]
Hi @bajtos, would like your approval/input on this PR

**Comment by bajtos** [comment]
> Hi @bajtos, would like your approval/input on this PR

Sorry @achrinza for a late reply, I have little time for LoopBack work these days. Your changes look reasonable, thank you for improving our GH Action setup! ❤️

**Pull request merged**
