### PR TITLE
chore - change prepublish to prepublishOnly

### PR DESCRIPTION
**Pull request by coderhaoxin**
`prepublish` scripts are deprecated

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@coderhaoxin thank you for the pull request. Could you please point us to the relevant documentation about `prepublish` and `prepublishOnly`? Most importantly, is `prepublishOnly` supported by the `npm` version shipped in Node.js 6.x LTS versions?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by coderhaoxin** [comment]
> the relevant documentation about prepublish and prepublishOnly

https://docs.npmjs.com/misc/scripts#deprecation-note

>  is prepublishOnly supported by the npm version shipped in Node.js 6.x LTS versions?

NO. `prepublishOnly` landed on `npm@4` 😢

**Comment by bajtos** [comment]
> NO. prepublishOnly landed on npm@4

That's bad. LoopBackNext supports Node.js 6.x for development, at least so far.

Can we perhaps use `prepack` instead of `prepublishOnly`? Is that supported by `npm@3`? Unfortunately the documentation does not make it clear when different scripts/hooks were added :(

**Comment by coderhaoxin** [comment]
> Can we perhaps use prepack instead of prepublishOnly? Is that supported by npm@3? 

https://github.com/npm/npm/blob/latest/CHANGELOG.md#v500-2017-05-25

`prepack` supported by `npm@5` 😢

**Comment by bajtos** [comment]
Well, then I don't see how to get rid of "prepublish" while keeping support for Node.js 6.x :(

**Comment by bajtos** [comment]
I am closing this pull request unmerged, because there does not seem to be any clean way how to support both Node.js 6.x and 8.x

**Pull request closed without merging**
