### PR TITLE
fix(docs): add new extensions to community extensions page

### PR DESCRIPTION
**Pull request by samarpanB**
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>

Added new community extensions 

See also #6528 

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by achrinza — APPROVED** [review]

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@samarpanB, thanks for the PR. 
Kicking off the CI again for the node.js14 failure one.

**Comment by dhmlau** [comment]
@samarpanB, thanks for your contribution. Your PR has landed! 🎉

**Comment by samarpanB** [comment]
@dhmlau when will this be published ?

**Comment by dhmlau** [comment]
@samarpanB, the docs was published to `@loopback/docs` but there seems to be some issue to have them refreshed on loopback.io. Looking into it. See PR https://github.com/strongloop/loopback.io/pull/1167/.

**Comment by dhmlau** [comment]
@samarpanB, the refresh problem has been resolved. Please check it out: https://loopback.io/doc/en/lb4/Community-extensions.html.

**Pull request merged**
