### PR TITLE
refactor: Move metadata.ts to openapi-spec[WIP]

### PR DESCRIPTION
**Pull request by jannyHou**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by raymondfeng** [comment]
@jannyHou Please hold off until https://github.com/strongloop/loopback-next/pull/775 is landed. The REST related metadata code has been significantly changed.

**Comment by jannyHou** [comment]
@raymondfeng Sure, just about to ask you should I wait. There are still some discussion about routing and I am still updating it to openapi3, so take your time on the decorator refactor.

**Comment by raymondfeng** [comment]
@jannyHou https://github.com/strongloop/loopback-next/pull/775 has been merged.

**Comment by jannyHou** [comment]
closed in favour of https://github.com/strongloop/loopback-next/pull/804

**Pull request closed without merging**
