### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skyebook**
Fix link to lb4 docs

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
Please sign the cla

**Comment by skyebook** [comment]
Sorry, done

**Comment by raymondfeng** [comment]
Can you also reformat the commit message per https://github.com/strongloop/loopback-next/wiki/Contributing#guidelines? If you want me to do so, please let me know.

**Comment by raymondfeng** [comment]
@skyebook Please sign CLA at https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by skyebook** [comment]
@raymondfeng commit message fixed

**Comment by raymondfeng** [comment]
@skyebook Thank you for the contribution! I'll merge it once the CI is passing.

**Pull request merged**
