### PR TITLE
refactor(repository): remove underscore from hasOne protected method

### LINKED ISSUE #2370: Removed underscore from hasOne protected method
Somehow removing the underscore from the hasOne protected method got missed.

### PR DESCRIPTION
**Pull request by codejamninja**
Removed underscore from hasOne protected method

Fixes #2370
See also #2112, #2091

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by codejamninja** [comment]
The documentation is updated, but I think I failed to update some integration tests. I'll take of it.

**Comment by codejamninja** [comment]
I updated the examples

**Comment by codejamninja** [comment]
Should be good to go now

**Comment by jannyHou** [comment]
@codejamninja Sorry one more thing, could you squash the 4 commits into one? Almost there! Thanks.

**Comment by codejamninja** [comment]
@jannyHou are you not able to squash and merge when you accept the pull request? It's rather inconvenient for me to rebase everything into one single commit. That's why GitHub added the squash and merge feature.

https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

**Comment by bajtos** [comment]
> are you not able to squash and merge when you accept the pull request? It's rather inconvenient for me to rebase everything into one single commit. That's why GitHub added the squash and merge feature.

We want to run our CI to verify that the final commit message is following our commit guidelines. When squashing via GitHub UI, it's too easy to accidentally create a commit that's violating them.

We can do the final squash & rebase ourselves by leveraging another GitHub feature, see https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/ However, it's easier for us if the contributor can do it themselves, because we have more contributors than maintainers.

**Comment by bajtos** [comment]
Landed, thank you for the contribution 👏

**Pull request merged**
