### PR TITLE
refactor: remove passport dependencies from authentication package

### PR DESCRIPTION
**Pull request by emonddr**
Remove all passport-related dependencies and mocha tests
now that the LoopBack passport adapter has been revised
and moved to its own independent package.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by emonddr** [comment]
The coveralls complaint about a decrease in coverage had nothing to do with authentication package... so I merged my PR with Diana's consent.

**Comment by bajtos** [comment]
@emonddr isn't this a backwards-incompatible change requiring a new semver-major release? I mean before your change, it was possible to `import {StrategyAdapter} from '@loopback/authentication'` and then define a passport-based strategy using the adapter. That code will break after your changes are published to npm registry.

**Comment by privateOmega** [comment]
@bajtos Can this be handled like by importing strategyadapter from **@loopback/authentication-passport** and then defining passport-based strategy like `const strategyAdapter = new StrategyAdapter(strategy, 'jwt-strategy');`

**Comment by bajtos** [comment]
> Can this be handled like by importing strategyadapter from **@loopback/authentication-passport** and then defining passport-based strategy like `const strategyAdapter = new StrategyAdapter(strategy, 'jwt-strategy');`?

**Comment by bajtos** [comment]
> Can this be handled like by importing strategyadapter from **@loopback/authentication-passport** and then defining passport-based strategy like `const strategyAdapter = new StrategyAdapter(strategy, 'jwt-strategy');`?

IDK, I am not familiar with the details of our authentication & authentication-passport packages 🤷‍♂

**Pull request merged**
