### PR TITLE
Fixes typo in "sequence"

### PR DESCRIPTION
**Pull request by VergilSkye**
There is a typo in the word "sequence", it was written as "sequnce" at line 183.

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [X] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@VergilSkye, thanks for catching the typo. Could you please sign the commit by running `git commit --amend -s`? For details, see https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco. Thanks.

**Review by jannyHou — COMMENTED** [review]
@VergilSkye  Thanks! Please sign off your commit according to https://loopback.io/doc/en/contrib/doc-contrib.html#signing-off-commits-using-dco.

**Comment by VergilSkye** [comment]
Thanks for the review @dhmlau and @jannyHou. I followed the instructions and I hope everything is all right. Sorry for the delay

**Comment by dhmlau** [comment]
@VergilSkye, thanks for taking care of this issue. Each commit needs to have a DCO signoff. However, in your case, I think you can just squash the commit.

**Comment by dhmlau** [comment]
@VergilSkye, i saw you have signed both commits, not sure why the DCO bot is complaining. Anyway, I've squashed the commits for you, see if CI passes this time.

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@VergilSkye, thanks for your contribution. Your PR has landed. 🎉

**Pull request merged**
