### PR TITLE
fix(testlab): Remove start call from createClientForRestServer

### PR DESCRIPTION
**Pull request by kjdelisle**
### Description

This aligns this creation function with requirements for creating
applications in loopback using the rest package. Applications
will start their registered servers, so this function will no
longer do so.

#### Related issues
#613 -- The Testing-Your-Application.md doc will advise a valid design pattern that the current code cannot satisfy, which is what this fix provides.

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by kjdelisle** [comment]
Since all of the code internal to the loopback monorepo no longer makes use of this function, there weren't any tests to modify.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by bajtos** [comment]
Also note that most of the content in Testing-Your-Application.md will be gone soon - see https://github.com/strongloop/loopback-next/issues/553

**Comment by kjdelisle** [comment]
>what if somebody creates a Server instance differently (not via app.start) and wants to create a client for it?

```ts
const server = new RestServer();
server.bind(RestBindings.PORT).to(3001);
server.start();
const client = await createClientForRestServer(server);
// do stuff with client!
```

The issue I was having was that I no longer had *control* over when I would start my server instance; the helper function was deciding for me. This way, you can spin the server up before *or* after you've created the client to test it.

**Comment by kjdelisle** [comment]
>Implement a flag/property allowing us to check whether the server is running (has been started and hasn't been stopped). Modify this test helper to skip server.start() if it's already running. Also, server.start() should thrown an error if it has been already started.

I was already thinking of adding an `isRunning` function to the Server interface so that all implementations must provide a function to determine their status, though I wasn't yet sure if we wanted it to simply be a boolean check or if we wanted to track states (starting, started, stopping, stopped, etc)

**Comment by bajtos** [comment]
> This way, you can spin the server up before or after you've created the client to test it.

The tests should be using an ephemeral port (listen on port 0, let the OS assign a free port number), otherwise we may get conflicts with other processes listening on the same port. In that case, you cannot create a client before the server is started, because we don't know the URL (the port number) before start.

> I was already thinking of adding an isRunning function to the Server interface so that all implementations must provide a function to determine their status, though I wasn't yet sure if we wanted it to simply be a boolean check or if we wanted to track states (then it would be a different name, and would have states like starting, started, stopping, stopped, etc)

I think we used to have a state property sometime in the past. I'd personally follow YAGNI principle and start with `isRunning` property. We can always add more states and change `isRunning` to a getter calling something like `return this.state === ServerState.RUNNING`.

**Comment by bajtos** [comment]
This PR looks pretty much abandoned to me, I am closing it. @kjdelisle feel free to reopen if/when you get time to work on this again.

**Pull request closed without merging**
