### PR TITLE
fix(security): support type number in securityId

### PR DESCRIPTION
**Pull request by frbuceta**
I have a model with the id of type number and I have to change it to string and then change it back to number. Hence this PR

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@frbuceta The `UserProfile` is an open interface. If you need to use `number` as the user id, can you just have a `getter` for `[securityId]` to return string value?

**Comment by frbuceta** [comment]
> @frbuceta The `UserProfile` is an open interface. If you need to use `number` as the user id, can you just have a `getter` for `[securityId]` to return string value?

How would I do something like that?

**Comment by raymondfeng** [comment]
```ts
const userProfile: UserProfile = {
  get [securityId]() { return String(this.id); },
  id: 123
}
```

**Comment by frbuceta** [comment]
> ```ts
> const userProfile: UserProfile = {
>   get [securityId]() { return String(this.id); },
>   id: 123
> }
> ```

Of course but I have an id of type number that I pass to string and when I get it back I need it in number

```ts
const x: UserProfile = {
  get [securityId]() { return parseInt(this.id); },
  set [securityId](value) { this.id = value },
  id: '123'
}
```
This does not work

**Comment by frbuceta** [comment]
I have deleted a comment. I was doing the same as you but different I already understand

**Comment by frbuceta** [comment]
I close the PR and leave comments for future questions of the users

**Pull request closed without merging**
