### PR TITLE
Fixing tests for windows and added lint:fix task

### PR DESCRIPTION
**Pull request by el-davo**
cc @bajtos @raymondfeng @ritch @superkhau Following discussions on https://github.com/strongloop/loopback-next/pull/251#issuecomment-299046532. This fixes https://github.com/strongloop/loopback-next/issues/164 and added a lint:fix task to automatically try and fix lint issues

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by el-davo** [comment]
Not sure whats up with the commit Linter :

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@el-davo thank you for the pull request.

The commit linter complains when a commit message does not follow our [50/72 style](http://loopback.io/doc/en/contrib/git-commit-messages.html).

> Merge branch 'master' of https://github.com/el-davo/loopback-next

This may have confused our CI checks too. We don't use merge commits, but rebase on top of the latest master instead (`git rebase master && git push -f`).

I fixed those issues for you.

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Pull request merged**
