### PR TITLE
fix(boot): warn if attempts to call app.repository without RepositoryMixin

### PR DESCRIPTION
**Pull request by virkt25**
console warning is excessive / clutters the logs for users. For someone not using the RepositoryMixin, they can enable debug to help identify the issue.

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] Related API Documentation was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

**Comment by bajtos** [comment]
I personally prefer frameworks to be noisy when I am doing something stupid, therefore `console.warn` is better than `debug` to me.

I understand that applications intentionally not using repositories should not see this warning. Shouldn't these applications configure boot in such way that the repository booter is not used?

 - If my app is using repositories, then I should configure repository booter and use `WithRepository` mixin. If I forget to use the mixin, then the booter will helpfully remind me of the problem.

 - If my app is not using repositories, then I should configure the bootstrapper to exclude repository booter. No warning is printed in such case.

Thoughts?

**Comment by raymondfeng** [comment]
I agree that we should not switch to `debug` as a fix.

My take is to only warn users right before `app.repository()` has to be called. In this case, the app does not have any repositories and RepositoryBooter.discover() should return an empty list. As a result, no `app.repository()` is required and no warning should be issued.

**Comment by virkt25** [comment]
The reason the warning comes everytime right now is that `RepositoryBooter` is part of the default `booters` list of the `BootComponent`. So a project using `BootMixin` automatically gets configured with `RepositoryBooter` and the reason for doing so was to provide a better user experience, the default booters should be loaded and configured to our default conventions automatically imo. Provides some level of magic.

I think an alternative (and maybe what @raymondfeng meant) would be to have `RepositoryBooter` warn a user only if repositories are discovered but the Mixin is missing ... but in that case I think I would prefer to throw an error. This way they still have the magic of being able to add repositories when ready and get those booted automatically ... and get a warning / error if they forget to add `RepositoryMixin`.

**Comment by raymondfeng** [comment]
> I think an alternative (and maybe what @raymondfeng meant) would be to have RepositoryBooter warn a user only if repositories are discovered but the Mixin is missing ... but in that case I think I would prefer to throw an error. This way they still have the magic of being able to add repositories when ready and get those booted automatically ... and get a warning / error if they forget to add RepositoryMixin.

Yes, that's what I meant. We only issue a warning or error if repositories are discovered. In summary:

1. No repositories, no RepositoryMixin - No warning or error
2. No repositories, yes RepositoryMixin - No warning or error
3. Yes repositories, no RepositoryMixin - Warning or error (I prefer warning as it's possible to use the repository without calling `app.repository`.

**Comment by raymondfeng** [comment]
This discussion makes me to think if calling `app.*` to register specific types of artifacts is a good design:

1. The registration behavior is contributed as a mixin from extensions such as `rest`. There is no hard dependency on `Application`. Only `Context` is good enough. The booter can just call `bind`.

2. It may be better to use the extension point pattern. For example, app.register('controller', controllerClass) or app.register('repository', respositoryClass).

**Comment by virkt25** [comment]
I've updated the PR to warn a user if a repository is found without a RepositoryMixin. 

The reason for using the `app.repository` is to make sure boot picks up changes to the binding key that might be used ... or change in tags, etc. 

I agree that we should add a simpler sugar method like the one you proposed (`app.register('type', ArtifactClass)`) and a BindingKeys file in the package can export a `const` for the `type`. 

I do think that's out of the scope of this PR however.

**Comment by raymondfeng** [comment]
> I do think that's out of the scope of this PR however.

Do you want to create an issue to track that?

**Comment by virkt25** [comment]
Done. Please see https://github.com/strongloop/loopback-next/issues/1080

**Pull request merged**
