### PR TITLE
docs: Throw error instead of returning rejected promise

### PR DESCRIPTION
**Pull request by joeytwiddle**
I recommend `throw` over `return Promise.reject()` because:

1. It is shorter, which makes it easier to read.
2. It retains some parity between synchronous and asynchronous code. (It will continue to work as expected if those lines were extracted into a synchronous function.)

There are [some occasions](https://gist.github.com/joeytwiddle/21331531f50885345e063d59ec7f11f2) when you cannot use `throw` in place of returning a rejection, but if you are in the body of an async function then it is always safe.

If you have considered this style but rejected it, I would be interested to learn your reasoning, if it happens to be available online somewhere. Cheers!

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by joeytwiddle** [comment]
I have changed those bits of the code that I could. There are some cases where a function is not async and cannot be made async without changing its behaviour. In that case I thought it was best not to change.

Please do check with your colleagues that they are happy with this style. Cheers!

**Comment by bajtos** [comment]
@joeytwiddle this is great, thank you for the contribution!

Initially, I was using `Promise.reject` instead of `throw` because I believed it was faster that way. V8's performance has come a long way since the time we started loopback-next in January 2017 and AFAIK, `throw` statements are no longer triggering de-optimization and therefore they should not have any performance impact anymore.

The proposed changes look good to me 👍 

It would be great to capture this style convention in our documentation for people developing loopback-next. Unfortunately we don't have a proper style guide yet (loosely related: https://github.com/strongloop/loopback-next/issues/950), the best place where to describe this convention is here: [pages/en/contrib/style-guide.md](https://github.com/strongloop/loopback.io/blob/18ff53334766ce7f8664cc55bea5f18decb95eaf/pages/en/contrib/style-guide.md). Would you mind opening a pull request against loopback.io repository and adding a new entry to that file?

**Comment by bajtos** [comment]
We should squash the first three commits into a single one before landing this patch. Only the latest commit fixing prettier formatting should be preserved standalone.

**Comment by bajtos** [comment]
Landed, thank you @joeytwiddle again for your contribution ❤️ 

I'll review strongloop/loopback.io#669 ASAP.

**Pull request merged**
