### PR TITLE
fix(docs): Fix path name in todo-list-tutorial-controller.md

### PR DESCRIPTION
**Pull request by jtlindsey**
Changes based on what i saw after running `lb4 example todo-list` to see what I might be missing while trying to follow the tutorial. There is no `src/models/todo-list.controller.ts` but there is a `src/controllers/todo-list.controller.ts`.  This pull request probably doesn't correct all the issues for this part of the tutorial. Somebody that is not new to loopback should check this page.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by jtlindsey** [comment]
Why trying to sign the "CLA"
```
504 ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. 
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-504-gateway-timeout.html). 
Generated by cloudfront (CloudFront)
Request ID: 4Rwk1QCZVyvBKJ0avc2cRdOfQqq7FxGTHxetIfFkkg8sHDf7XIWbbA==
```

**Comment by dhmlau** [comment]
@jtlindsey, CLA check seems to be good now. 

@slnode test please

**Comment by dhmlau** [comment]
@jtlindsey, thanks for your PR.  Your changes LGTM.  However, there's some linting error on the commit message. Could you please fix it? Thanks.
```
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
```

To include the `type` and `subject`, my suggested commit message would be below, feel free to modify: 
```
fix(docs): Fix path name in todo-list-tutorial-controller.md 
```

Here is our commit message guideline: https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines.

**Comment by dhmlau** [comment]
@jtlindsey, you don't want to continue with this PR? I can help you to fix the commit message if you want.

**Pull request closed without merging**
