### PR TITLE
test: increase timeouts to accomodate slow networks

### PR DESCRIPTION
**Pull request by bajtos**
See https://github.com/strongloop/loopback-next/issues/1407

## Checklist

- [x] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- API Documentation in code was updated
- Documentation in [/docs/site](../tree/master/docs/site) was updated
- Affected artifact templates in `packages/cli` were updated
- Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by raymondfeng** [comment]
Hmm, the `appveyor` CI fails with timeout - https://ci.appveyor.com/project/bajtos/loopback-next/build/1.0.5925-master/job/5gqw1lwv96pqupnj

**Comment by bajtos** [comment]
> Should we consider increasing timeout at the top level describe instead of on particular tests? Otherwise in the future if more tests are added and run into the same issue, one might not remember the timeout needs to be increased.

I'd rather not. IMO, we should closely investigate each test that's failing on a timeout and start by looking into ways how to make that test faster. If we increase the timeout for all tests, then we won't notice when a pull request is introducing more slow tests. That creates a sort of a tech debt, because over time we can end up with so many slow tests that our test suite becomes unusable and the cost of speeding it up will be too large.

**Comment by virkt25** [comment]
AppVeyor seems to have passed this time around. I find their CI system is usually much slower to run than Travis (possibly due to the OS). Anyways, looks good to land.

**Comment by hacksparrow** [comment]
Let's land this.

**Comment by virkt25** [comment]
@bajtos landed this for you so other PRs can be merged. 
cc: @hacksparrow

**Pull request merged**
