### PR TITLE
doc: add new package

### PR DESCRIPTION
**Pull request by jannyHou**
### Description:

Add some guide on the things to remember when create a new package.
Any other stuff worth mentioning here?

### CODE REVIEW

**Comment by jannyHou** [comment]
@shimks thanks!

Good point I will add them:

- LICENSE
- index files
- copyright years

It's not part of my task, just some notes, doesn't take big time to write.

**Comment by raymondfeng** [comment]
@jannyHou Good addition to the docs. I polished it to be the following.

### Add a new package

To add a new package, create a folder in [`packages`](packages) as the root directory of your module. For example,
```sh
cd loopback-next/packages
mkdir <a-new-package>
```
The package follows the node/npm module layout. You can use `npm init` or `lb4 extension` command to scaffold the module, copy/paste from an existing package, or manually add files including `package.json`.

We have some configuration files at the top level (**loopback-next/**):

- `.gitignore`
- `.prettierignore`
- `.nycrc.yml`

For consistency across all packages, do not add them at package level unless specific customization is needed.

Please also register the new package in the following files:
- Add the new package and your name as its owner in [CODEOWNERS](CODEOWNERS). 
- Add the new module in the `packages` list in [MONOREPO#packages](MONOREPO#packages).

By default, npm publishes scoped packages with private access. There are two options to make a new scoped package with public access.

Add the following section to `package.json`:
```json
  "publishConfig": {
    "access": "public"
  },
```
Explicitly publish the package with --access=public.
```sh
cd packages/<a-new-package>
npm publish --access=public
```

**Comment by jannyHou** [comment]
@raymondfeng thanks! Much better phrased than mine, I add your doc and @shimks 's suggestion in the new commit.

**Comment by bajtos** [comment]
Great stuff!

I'd like to keep as much of developer docs in `docs/DEVELOPING.md`, I am already moving parts of `MONOREPO.md` there - see #1015. As for things to do when adding a new package, here is my checklist: https://github.com/strongloop/loopback-next/blob/docs/improvements/docs/DEVELOPING.md#new-package-checklist

I am proposing the following steps:
 
 1. Land this pull request ASAP, ignore the changes I am proposing in my #1015 
 2. I'll update my patch to include the new content from this pull request.

**Comment by jannyHou** [comment]
Thanks @bajtos ! I rebased my PR and will land it when CI green to unblock your patch.

**Pull request merged**
