### PR TITLE
feat(cli): update translation message

### PR DESCRIPTION
**Pull request by candytangnb**
update 3q tvt translation message

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by agnes512 — APPROVED** [review]

**Comment by dhmlau** [comment]
@candytangnb, thanks for your PR. Could you please sign the commit by running the following command:
```
git commit --amend -s
```

Thanks.

**Comment by candytangnb** [comment]
@dhmlau  Done.

**Comment by candytangnb** [comment]
@agnes512 @dhmlau TVT final pass will begin on Sep 15. Could I know when could I get these translation updates in lb4?

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@candytangnb, your PR is good to go, we've having some CI issues, so trying to get pass that. 

We can plan to have a release around the time when GVT starts.

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@candytangnb, thanks for your contribution. Your PR has landed! 🎉

**Comment by candytangnb** [comment]
@dhmlau Thanks. TVT is done by language tester but not us.  If could not be ready by Sep 13(DEV time zone), then we could not prepare screenshot for TVT tester on Sep 14. Not sure if it is OK.

**Pull request merged**
