### PR TITLE
update todo tutorial model creation to match LB4 GA

### PR DESCRIPTION
**Pull request by Boussama**
## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by b-admike** [comment]
@Boussama Can you please prefix your commit with `docs:` so that commit linter passes and rebase against latest master? You can check out https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#commit-message-guidelines on how to structure commit messages and https://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request on how to rebase your branch.

**Comment by raymondfeng** [comment]
@Boussama Thanks! I rebased your PR against master and committed via https://github.com/strongloop/loopback-next/commit/83441de26087f29b5fbea51b50df28bc93a9f71b.

**Comment by bajtos** [comment]
FWIW, this is the commit that was landed to master: b346d8c42

@raymondfeng in the future, it would be best if you could update the pull request branch with the changes and merge the changes via GitHub's green Merge button. That way we run a full CI check on the final code and GitHub marks the pull request as merged (not closed). Learn more here: https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by bajtos** [comment]
@Boussama thank you for the contribution! ❤️

**Pull request closed without merging**
