### PR TITLE
docs: modify sidebar

### PR DESCRIPTION
**Pull request by dhmlau**
Modify sidebar as proposed in PR https://github.com/strongloop/loopback-next/pull/3164.

Current side:

current-sidebar

New sidebar: 
new-sidebar

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
Is it the only difference to add a new `Overview`?

**Comment by dhmlau** [comment]
> Is it the only difference to add a new Overview?

much more. :) 
- `Overview` is the only item I added.  
- I've removed: FAQ and Glossary.  @bschrammIBM mentioned a while ago and I tend to agree with her that those two pages aren't very useful.  We have `key concepts` that are duplicate of `glossary`.
- For others, I've rearranged per the proposal.

**Comment by dhmlau** [comment]
@raymondfeng , I'd like to get the simpler/less controversial changes in this PR first, and then make a bigger refactoring for the `key concepts` and other section.

**Comment by hacksparrow** [comment]
**API Docs** should stand out as a separate list at the top or bottom of the list shown. The most crucial link can't be "lost" somewhere down the list.

**Comment by dhmlau** [comment]
There's a `API Docs` at the top of the page, as part of the template.  
However, it is pointing to apidocs.loopback.io.  If someone is using LB4 and click that link, he/she will be asked to click another link for the LB4 API docs. I guess the best way is to move the API docs completely (with LB3) to our docs.

**Comment by raymondfeng** [comment]
Should we move `Tutorials` down?

**Comment by dhmlau** [comment]
sure. where to?

**Comment by dhmlau** [comment]
@raymondfeng, I've moved down the Tutorial section. PTAL. Thanks.
Screen Shot 2019-07-12 at 2 24 13 PM

**Pull request merged**
