### PR TITLE
Refactor Context/Binding into @loopback/ioc

### PR DESCRIPTION
**Pull request by bajtos**
Now that we have better understanding of how IoC Container fits into our framework design, I'd like to make it a standalone package.

I consider this as a preparation step for my work on #142 `@inject` support for ctor args.

Connect to #142

cc @bajtos @raymondfeng @ritch @superkhau

### CODE REVIEW

**Comment by bajtos** [comment]
@raymondfeng @ritch @superkhau

While we are making this change, I am proposing to rename `Context` to `Container`. I believe `Container` is the name used by most (if not all) other Inversion of Control implementations.

**Comment by bajtos** [comment]
Connect to #142

**Comment by raymondfeng** [comment]
+1 to have a separate module for `ioc`. 

For naming, maybe we should define `Container` as an interface and `Context` as our implementation of `Container`?

**Comment by ritch** [comment]
PR LGTM - but I don't like the name...

> For naming, maybe we should define Container as an interface and Context as our implementation of Container?

`@loopback/context` should be the name

It should export

```ts
export interface Container {
}

export class Context implements Container {
}
```

Lets resolve both points in a different PR... going to merge this as is for now.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by superkhau** [comment]
I agree with @raymondfeng's proposal on Container as the interface and Context as our impl.

**Pull request merged**
