### PR TITLE
Docs/finish migration from loopback.io

### PR DESCRIPTION
**Pull request by shimks**
There are a couple of stray pages that haven't been migrated and updated over to the monorepo. The PR fixes this
- brings over commits made from Feb 23rd to Mar 15th, 2018.
  - https://github.com/strongloop/loopback.io/pull/634
  - https://github.com/strongloop/loopback.io/pull/636
  - https://github.com/strongloop/loopback.io/pull/631
  - https://github.com/strongloop/loopback.io/pull/637
  - https://github.com/strongloop/loopback.io/pull/621
  - https://github.com/strongloop/loopback.io/pull/640
  - https://github.com/strongloop/loopback.io/pull/642
  - https://github.com/strongloop/loopback.io/pull/638
  - https://github.com/strongloop/loopback.io/pull/624
  - https://github.com/strongloop/loopback.io/pull/635
  - https://github.com/strongloop/loopback.io/pull/644
  - https://github.com/strongloop/loopback.io/commit/2de9395134547467226d8ff7e1083c7e7af25a4f
- first commit is the actual migration itself
- second one changes hyperlinks from `.html` to `.md`
- third commit migrates over the sidebar and the CLI tables

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] Related API Documentation was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

**Comment by b-admike** [comment]
@virkt25 it'll just be to move them to their appropriate place, so that references are not broken. Also, @shimks what do you think about moving https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb4/includes/CLI-std-options.md?

**Comment by shimks** [comment]
@b-admike I think I want to keep that where is; it's not a file that needs to be changed frequently, and if we do need to change it, we can deal with that when we need to. Speaking of, we may need to componentize or comment your code in [update-lb4-docs.js](https://github.com/strongloop/loopback.io/pull/643/files#diff-015a67e879f2083136bcd7796abb4f33) so that it's easier to modify or add other specific files for anyone that may need to add to the script in the future.

**Comment by b-admike** [comment]
Fair enough. I've added comments to the script as you suggested, PTAL :-)

**Comment by shimks** [comment]
@raymondfeng Can I get you to sign off on this before I merge it? Thanks

**Comment by shimks** [comment]
@b-admike I agree. l'll make the change

**Comment by shimks** [comment]
Could I clarification as to why we need to make the change to `include_relative`? Is it even possible to parse this html stuff in github? If so, is this accounted for in your PR so that it changes it back to `{% include content/lb4-project-commands.html %}`?

**Comment by b-admike** [comment]
Oh it's because right now they are included from the top level of `loopback.io` and are inside `_includes/content`, but I want us to have the tables in `pages/en/lb4/includes/tables` and include them from there instead. What do you think?

**Comment by b-admike** [comment]
Once we hash out the details in this PR, I'll push up the changes to incorporate what we've done here.

**Comment by shimks** [comment]
That sounds good to me, I'll make the changes.

**Pull request merged**
