### PR TITLE
docs: remove summary frontmatter

### PR DESCRIPTION
**Pull request by hacksparrow**
Let's not include summary frontmatter in LB4 docs. Most of the pages do not contain them, and those which do create redundant text as shown in the screenshot.

> LoopBack 4 Todo Application Tutorial - Integrate with a geo-coding service

image

### CODE REVIEW

**Comment by hacksparrow** [comment]
@achrinza indeed! Thanks for the suggestion.

**Comment by nabdelgadir** [comment]
To add to this, we should also try to make sure that the summaries are not just a paraphrase/copy of the title.

**Comment by dhmlau** [comment]
@hacksparrow, are we going to keep the summary fo SEO reason?

**Comment by hacksparrow** [comment]
Closing this, will open another PR with the UI fix.

**Pull request closed without merging**
