### PR TITLE
RFC: enable no-untyped-public-signature

### PR DESCRIPTION
**Pull request by bajtos**
eslint-typescript recently introduced a new rule [no-untyped-public-signature](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-untyped-public-signature.md).

I'd like to discuss whether we want to enable it. We have more than 200 violations of this rule in our current code base and unfortunately there is not automatic fixer available. Before I go ahead and manually fix all violations, I'd like to get consensus that we want to enable the rule.

Why would we want to enable it? In my experience, code with missing type information is difficult to read. When LB users are trying to learn about our public API from our code, they have difficult times figuring out what are the methods and functions returning when the return type is not explicitly described.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by agnes512** [comment]
+1 to enable the new rule. I noticed that not all of functions have API docs. The type would be helpful to learn what a function actually does.

**Comment by raymondfeng** [comment]
I'm neutral on this:

1. Adding explicit return type for public methods make the code easier to understand.
2. TypeScript can infer the return type - I assume tsdocs use the inferred type.
3. The method signature is a bit longer and verbose.

**Comment by jannyHou** [comment]
I also agree on enabling this rule to ensure the consistency within a function's callers.

**Comment by bajtos** [comment]
I have revisited my priorities and feel this pull request requires more effort than I am willing to invest in the next few weeks. Feel free to pick up the work where I left.

**Pull request closed without merging**
