### PR TITLE
fix: generated REST middleware sequence

### PR DESCRIPTION
**Pull request by achrinza**
see #6953

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@achrinza I don't see why adding `@injectable()` helped. Please provide some explanation. Thanks.

**Comment by achrinza** [comment]
Classes that extend but are not decorated with `@injectable()` will cause LB4 to bind the base class (i.e. `MiddlewareSequence` instead of `MySequence`) (see #6918).

**Comment by raymondfeng** [comment]
@achrinza https://github.com/strongloop/loopback-next/pull/7005 should be the real fix.

Adding `@injectable()` in the subclass just hides the problem and it has side effects as it makes the generated sequence not a singleton anymore.

**Comment by achrinza** [comment]
> and it has side effects as it makes the generated sequence not a singleton anymore.

Is there a reason why it's no longer Singleton? Does this apply to other extended artifacts (i.e. Models, Controllers, Services)? I was under the assumption that `@injectable()` would function identically as if it were applied to a non-extended class.

**Comment by raymondfeng** [comment]
> Is there a reason why it's no longer Singleton? Does this apply to other extended artifacts (i.e. Models, Controllers, Services)? I was under the assumption that @injectable() would function identically as if it were applied to a non-extended class.

The base class has `@injectable({scope: BindingScope.SINGLETON')`. Now the sub class is decorated with `@injectable()`, which overrides the base class binding metadata and the binding scope is reset to the default value (`BindingScope.TRANSIENT`). We'll have to apply `@injectable({scope: BindingScope.SINGLETON')` to `MySequence` too.

**Comment by raymondfeng** [comment]
@achrinza Are we good to close this PR as https://github.com/strongloop/loopback-next/pull/7005 has landed?

**Comment by achrinza** [comment]
Yup, thanks for clarifying!

**Pull request closed without merging**
