### PR TITLE
fix(repository): returns null if no related model instance found for HasOne relation

### LINKED ISSUE #2472: DefaultHasOneRepository.get method throws exception if no match found
## Description
I have the following two models and HasOne relation for them:

```
@model()
export class Study extends Entity {
  @property({
    type: 'number',
    id: true,
    generated: true,
  })
  id?: number;

  @hasOne(() => Report)
  report?: Report;

  constructor(data?: Partial<Study>) {
    super(data);
  }
}
```

```
@model()
export class Report extends Entity {
  @property({
    type: 'number',
    id: true,
    generated: true,
  })
  id?: number;

  @belongsTo(() => Study)
  studyId: number;

  constructor(data?: Partial<Report>) {
    super(data);
  }
}
```
When I'm trying to access `report` with the following code:
`const report = await this.studyRepository.report(foundStudy.id).get()`
if there is no report for the `foundStudy` model, it will throw an exception

## Current Behavior
Throws exception for HasOne relation if no match found

## Expected Behavior
Returns null or undefined for HasOne relation if no match found.

According to the HasOneRepository interface, it should return null if no match found
```
export interface HasOneRepository<Target extends Entity> {
  /**
   * Find the only target model instance that belongs to the declaring model.
   * @param filter Query filter without a Where condition
   * @param options Options for the operations
   * @returns A promise of the target object or null if not found.
   */
  get(
    filter?: Pick<Filter<Target>, Exclude<keyof Filter<Target>, 'where'>>,
    options?: Options,
  ): Promise<Target>;
}
```

However, the DefaultHasOneRepository implementation throws an exception if no match found.
```
export class DefaultHasOneRepository<
  TargetEntity extends Entity,
  TargetID,
  TargetRepository extends EntityCrudRepository<TargetEntity, TargetID>
> implements HasOneRepository<TargetEntity> {

  async get(
    filter?: Pick<Filter<TargetEntity>, Exclude<keyof Filter<TargetEntity>, 'where'>>,
    options?: Options): Promise<TargetEntity> {
   // other codes
    if (found.length < 1) {
      // We don't have a direct access to the foreign key value here :(
      const id = 'constraint ' + JSON.stringify(this.constraint);
      throw new EntityNotFoundError(targetRepository.entityClass, id);
    }
    return found[0];
  }
}
```

### PR DESCRIPTION
**Pull request by shazha**
fix #2472

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by bajtos** [comment]
Hi @shazha, thank you for the pull request. I am afraid the current implementation is intentional and it's just the tsdoc comment that needs fixing.

You can read through the discussion in https://github.com/strongloop/loopback-next/pull/1658 to better understand our reasoning.

I can see how it can be useful to allow `hasOne` relation to support optional target and return `null` or `undefined` when there is no target model associated with the source instance. Let's discuss this 
#2472.

**Comment by bajtos** [comment]
@shazha ping, what's the status of this pull request? Are you still keen to work on this change?

**Comment by shazha** [comment]
@bajtos Sorry for didn't get back to it in time. I checked the latest source code and the comment is already fixed. I figured that you could close this PR directly 😀

**Comment by dougal83** [comment]
Closing as appears no longer relevant.  Relevant source has been updated.

**Pull request closed without merging**
