### PR TITLE
feat(cli): improve file structure for generated datasources (json/ts)

### PR DESCRIPTION
**Pull request by raymondfeng**
Improve file structure for datasources - extracted from #4051 

Triggered by https://github.com/microsoft/TypeScript/issues/34761

See https://github.com/strongloop/loopback-next/pull/4051#pullrequestreview-313211733

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
My response to https://github.com/strongloop/loopback-next/pull/4051#pullrequestreview-313211733:

Two options are proposes so far:

1. Rename the `*.datasource.json` files to avoid conflict.
2. Inline the json config into `*.datasource.ts` file

I see a 3rd option:
1. Keep a separate json file for datasource configuration
2. Improve datasource booter to use `app.configure()` to register configuration for datasources
3. In `*.datasource.ts` files, use `@config` to inject configuration into the class

**Comment by raymondfeng** [comment]
I'm proposing to rename `*.datasource.json` to `*.datasource.config.json` as the short term solution so that we can fully support TypeScript 3.7.x soon.

**Comment by raymondfeng** [comment]
@bajtos Please review.

**Comment by raymondfeng** [comment]
@dhmlau See https://github.com/strongloop/loopback4-example-shopping/pull/365.

I don't see it as a breaking change as existing code continues to import from `*.datasource.json`. The PR only impacts how datasource files are generated.

**Comment by bajtos** [comment]
> I'm proposing to rename `*.datasource.json` to `*.datasource.config.json` as the short term solution so that we can fully support TypeScript 3.7.x soon.

:+1:


> In `*.datasource.ts` files, use `@config` to inject configuration into the class

I was thinking about `@config` too, let's leave that out of scope of this pull request though.

**Comment by bajtos** [comment]
> Does it consider as a breaking change?

I don't consider this as a breaking change for the reasons explained by @raymondfeng above.

However, I think we need to clearly communicate this change and explain our users how is it affecting their exiting projects, what is the migration path and how urgent the upgrade is.

I think a short blog post (independent of our milestone blog) would be ideal.

**Pull request merged**
