### PR TITLE
docs: improvements on acronym consistency; updated graphic

### PR DESCRIPTION
**Pull request by damon-shaw**
The changes made by this pull request aim to improve the consistency and readability of the [Inside a LoopBack Application](https://loopback.io/doc/en/lb4/Inside-LoopBack-Application.html) page. It includes an updated graphic, which can be adjusted if needed.

It makes the following changes:
* replaces instances of `api` with `API` (except in code or URLs, of course)
* replaces instances of `jwt` with `JWT`
* replaces "userId" with "`userId`" for clarity
* removes redundant use of "token" (e.g. "jwt token" <-> "JSON Web Token token")
* replaces the "Model and Relations" graphic with one that's easier to read and uses lines that represent the type of relation

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

These changes do not involve any new or changed code, only updates to the documentation.

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
btw, there's a code lint error. Could you please fix it by running `npm run lint:fix`? Thanks.

**Comment by damon-shaw** [comment]
Sorry about the linting issue. I've run `npm run lint:fix`, which caused all of the files to be marked as modified, though no observable changes in these files could be found. I've only committed `docs/site/Inside-Loopback-Application.md`, where a change made by the linter _is_ evident.

Here are some alternative organizations for the relations example graphic. Let me know if you like one of these better.

_This one is my interpretation of what you described (2 models per row)..._

____
_This one is closer to how the models in the current graphic are laid out..._

**Comment by dhmlau** [comment]
@damon-shaw, thanks for fixing the lint issue. The first diagram in [your above comment](https://github.com/strongloop/loopback-next/pull/5560#issuecomment-633894093) LGTM. Could you please update it in the PR and merge the changes? Thanks.

**Comment by dhmlau** [comment]
@damon-shaw, I squashed the commits for you, and the PR is ready to land.

**Comment by dhmlau** [comment]
@damon-shaw, thanks for your contribution. Your PR has landed! 🎉

**Comment by damon-shaw** [comment]
@dhmlau Thanks for that. I saw your original message but wasn't able to get around to it.

Thanks for the approval and merge!

**Pull request merged**
