### PR TITLE
docs(DataSource-generator): Update DataSource-generator.md

### PR DESCRIPTION
**Pull request by jdegger**
Small error in documentation link.

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [X] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by hacksparrow** [comment]
@jdegger if you sign the CLA - https://cla.strongloop.com/agreements/strongloop/loopback-next and rebase, we should be able to land the PR.

**Comment by jdegger** [comment]
I can't sign it, it gives me a 504 after loading for a while. 

Request ID: zFY_5iJRvrcpV4DEl_nPHb_SybF67I5NlS7oFEa3oeAC0LzFMxn9HQ==

**Comment by hacksparrow** [comment]
> I can't sign it, it gives me a 504 after loading for a while.

@dhmlau @virkt25 any idea what's happening?

**Comment by virkt25** [comment]
CLA checks shows as signed.

**Comment by jdegger** [comment]
The whole CLA system is not working anymore. Getting all kinds of 404s. Where can I report this? Or do you report it internally?

**Comment by virkt25** [comment]
Thanks for the catch and the PR @jdegger 

For rebase, we normally do so by rebasing against the upstream:
```
git remote upstream https://github.com/strongloop/loopback-next.git
git fetch upstream
git rebase -i upstream/master
```

I've done this for you as well as fixed the commit message so it passes the commit linter. You can read about our commit message guidelines here for future contributions: https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#commit-message-guidelines

Once again, thanks for the contribution! :)

**Comment by virkt25** [comment]
You can report it to us by just commenting on a PR. That said, it's working fine for me and it shows that you've signed the CLA so I'm not sure what's going on.

**Comment by jdegger** [comment]
I tried to figure out all the contribution guidelines but honestly, there are a _lot_ for just fixing a typo in the docs. It might be easier to have a small overview of what you need to do for a PR, it was bit overwhelming now.

Thanks for approving :) hope to contribute more of course.

**Comment by jdegger** [comment]
PS: This is what I see on most CLA pages:

screen shot 2018-09-07 at 18 44 36

**Comment by virkt25** [comment]
> I tried to figure out all the contribution guidelines but honestly, there are a lot for just fixing a typo in the docs. It might be easier to have a small overview of what you need to do for a PR, it was bit overwhelming now.

I agree that it can be a bit much to read for a simple change and it's easier to just learn by doing ... that's why I fixed it for you, the explanation was to help you for the next PR. Can't wait to see more contributions from you :) and if anything isn't following the guidelines I'm ok to help you fix it :)

**Comment by virkt25** [comment]
Hmm, cc: @rmg any idea why the CLA might be acting up?

**Comment by rmg** [comment]
@virkt25 the good news is I figured it out (a bug in rails lazy loading).

@jdegger the bad news is your signature was lost in the process. Could you sign again? https://cla.strongloop.com/agreements/strongloop/loopback-next

**Comment by jdegger** [comment]
I got exactly the same result as the first time @rmg. Got a 504 after agreeing.

screen shot 2018-09-08 at 17 49 39

**Comment by rmg** [comment]
@jdegger that looks like a different error (possibly a side effect of the app scanning for your open PRs). Unfortunately, the logs aren't retained long enough for me to verify that now :-(

Rather than asking you to keep trying and report back, I'll just try to keep an eye open for similar reports. In the meantime, **I was at least able to verify that your signature is back on the list**, despite the error.

**Pull request merged**
