### PR TITLE
[RFC] feat(socketio): add support for Socket.IO to expose WebSocket endpoints

### PR DESCRIPTION
**Pull request by raymondfeng**
Starting to add SocketIOServer and explore how to decorate a controller to respond to corresponding events for incoming requests.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by bajtos** [comment]
+1 to explore socket.io integration 👍 

@raymondfeng to make review easier, can you treat this pull request as a spike please? It would be great to add `_SPIKE_.md` document to monorepo root and write down a high-level overview of the most important aspects of the implementation you are proposing.

**Comment by raymondfeng** [comment]
@bajtos I started to add more information into the [README](https://github.com/strongloop/loopback-next/blob/socketio/packages/socketio/README.md).

**Comment by octisfall** [comment]
@raymondfeng `npm install --save @loopback/socketio` returns 404

**Comment by bajtos** [comment]
I'd like to put this pull request on hold until we figure out how to approach experimental features - see https://github.com/strongloop/loopback-next/issues/2676

**Comment by raymondfeng** [comment]
Move to https://github.com/strongloop/loopback-labs/pull/4

**Comment by wiedzmin26** [comment]
@raymondfeng When will it be ready?

**Pull request closed without merging**
