### PR TITLE
feat(jwt): add roles to authentication-jwt module

### PR DESCRIPTION
**Pull request by odykyi**
## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by odykyi** [comment]
added roles like here 

https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/jwt-service.ts

**Comment by dhmlau** [comment]
@odykyi, thanks for the PR. Could you please take care of the following?
- fix commit message error. Please see the [commit message guidelines](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines).
- sign off the commit using DCO. See details in https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco.
- add tests to verify your changes.

Thanks!

**Comment by achrinza** [comment]
Merge commits seem to be screwing with the git history.

Please use reset back to master and re-apply changes.

Then use rebase instead of merge to apply upstream changes.

More info: https://loopback.io/doc/en/lb4/submitting_a_pr.html#6-rebasing

**Comment by achrinza** [comment]
Closing in favour of #6380

**Pull request closed without merging**
