### PR TITLE
docs(docs): has-one-relation typo corrected

### PR DESCRIPTION
**Pull request by milindsingh**
Doc has a typo in function name `createHasOneRepositoryFactoryFor` -> `_createHasOneRepositoryFactoryFor`

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by bajtos** [comment]
Hi @milindsingh, thank you for the pull request. The API `_ createHasOneRepositoryFactoryFor` has been deprecated in favor of `createHasOneRepositoryFactoryFor`, so the documentation is correct. I guess it's `examples/todo-list/src/repositories/todo-list.repository.ts` that needs to be fixed to use the new API.

**Comment by bajtos** [comment]
Oh, on the second thought, it looks like `createHasOneRepositoryFactoryFor` was not created yet. We use this new form for the following methods only: `createHasManyRepositoryFactoryFor` and `createBelongsToAccessorFor`.

So the problem should be fixed by modifying `DefaultCrudRepository` to implement `createHasOneRepositoryFactoryFor` and deprecate `_createHasOneRepositoryFactoryFor`.

**Comment by milindsingh** [comment]
@bajtos Thanks
 Can you update me about the ETA for `createHasOneRepositoryFactoryFor` to be implemented? as far as I now swagger explorer does not reflect the relation in response. #2209

**Comment by bajtos** [comment]
> Can you update me about the ETA for `createHasOneRepositoryFactoryFor` to be implemented? 

@b-admike you are working on relations, do you happen to know if there is any ETA for full has-one support?

@milindsingh Would you mind contributing the small improvement I described in my comment above?

_the problem should be fixed by modifying `DefaultCrudRepository` to implement `createHasOneRepositoryFactoryFor` and deprecate `_createHasOneRepositoryFactoryFor`._

> As far as I now swagger explorer does not reflect the relation in response. #2209

Let's keep this discussion inside https://github.com/strongloop/loopback-next/issues/2209.

**Pull request closed without merging**
