### PR TITLE
Update Model.md

### PR DESCRIPTION
**Pull request by logico-dev**
## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@logico-dev, thanks for catching this. Your change LGTM. Could you please sign the commit? 
You can run the following command:
```
git commit --amend -s
```

For details, please see https://loopback.io/doc/en/contrib/code-contrib.html.

**Comment by logico-dev** [comment]
@dhmlau Done!

**Comment by dhmlau** [comment]
I've squashed the commits and fixed the commit message. But the DCO check still fails even the commit seems to be signed. 
@strongloop/loopback-maintainers, please help if you know how it can be fixed. Thanks.

**Comment by achrinza** [comment]
Here's the error message:

> "Alejandro Amaral aamaral@logico.com.ar", but got "logico aamaral@logico.com.ar".

Use `git commit --amend` and modify the DCO line accordingly. Hope this helps and thanks for your contribution!

**Comment by achrinza** [comment]
Looks like there were some issues with the git history. I've cleaned it up so it should be good to land after the the checks pass.

Thanks again for your contribution!

**Comment by dhmlau** [comment]
I've run `npm run lint:fix` command and hopefully it fixes the code linting error.

**Review by dhmlau — APPROVED** [review]

**Review by achrinza — APPROVED** [review]

**Comment by dhmlau** [comment]
@achrinza, thanks for your help. :) 

@logico-dev, thanks for your contribution. Your PR has landed. 🎉

**Pull request merged**
