### PR TITLE
docs: Include code of TodoListTodoController instead of TodoListController

### PR DESCRIPTION
**Pull request by Hakier**
Updated documentation

### CODE REVIEW

**Comment by raymondfeng** [comment]
@Hakier Thank you for the contribution. CI fails due to invalid format of the commit message. Please follow https://loopback.io/doc/en/lb4/submitting_a_pr.html#how-to-submit-a-pull-request-pr-for-loopback-4 to fix it.

**Comment by Hakier** [comment]
> Code changes LGTM. Let's fix the commit message now.

@bajtos Can you fix it? I do not know what is bad with it and do not have currently time to investigate

**Comment by emonddr** [comment]
replaced by PR : https://github.com/strongloop/loopback-next/pull/2647

**Comment by raymondfeng** [comment]
Closed by https://github.com/strongloop/loopback-next/pull/2647

**Pull request closed without merging**
