### PR TITLE
refactor(cli): prompt for id name and type when they are not detected from model files

### PR DESCRIPTION
**Pull request by agnes512**
connects to #6017 and #6131

In spike 6017 we realized that current relation CLI frequently reads files, which causes lots of overhead. Apart from that, as it is reported in 6131, the current CLI couldn't handle some use cases such as inheritance. It only checks the primary keys by reading files instead of models themselves.

For the inheritance issues, now the CLI will prompt for name/type if it doesn't detect them from model files (suggested by https://github.com/strongloop/loopback-next/pull/6489#issuecomment-731017395). See [commit - code](https://github.com/strongloop/loopback-next/pull/6937/commits/318a965a29b9269495f2b8cc152b219f1e47bbc8) and [commit - tests](https://github.com/strongloop/loopback-next/pull/6937/commits/e4ca5fff506a6d48945c8ae3c36eec600b30db6a).

#### when id name and type are provided/detected
```
$ lb4 relation
? Please select the relation type hasMany
? Please select source model TodoList
? Please select target model Todo
? What is the name of ID property of the source model? id
? Source property name for the relation getter (will be the relation name) todos
? Allow TodoList queries to include data from related Todo instances? Yes
```

####  when id name and type are NOT provided/detected
```
$ lb4 relation
? Please select the relation type hasMany
? Please select source model TodoList
? Please select target model Todo
? What is the name of ID property of the source model? id
? What is the type of the source model primary key? number
? What is the name of ID property of the target model? id
? What is the type of the target model primary key? number
? Foreign key name to define on the target model todoListId
? Source property name for the relation getter (will be the relation name) todos
? Allow TodoList queries to include data from related Todo instances? Yes
```

This way it would not add friction for most of users. 

As for overhead of relation cli tests, with the new added options `sourceModelPrimaryKey`, `sourceModelPrimaryKeyType`, `destinationModelPrimaryKey`, and `destinationModelPrimaryKeyType`, relation cli tests could take them with options so that they don't need to read files over and over again. See [commit](https://github.com/strongloop/loopback-next/pull/6937/commits/bf79d1f4155fa22232d51f51aa4a17bce023f9c3)

With options, all CLI tests only take around 1m30s ( it was 2m30s before).

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by emonddr** [comment]
Hi @agnes512 , great work. Just wondering if someone doesn't use the CLI . What if they look at the docs and construct it by hand, do we have the necessary stuff in the docs to help them. Just curious. thx

**Review by emonddr — COMMENTED** [review]
Please see my comment about the scenario that user doesn't use the CLI. thx. Looks great.

**Comment by Salketer** [comment]
That's great @agnes512 ! Thank you for this.

**Comment by emonddr** [comment]
@Salketer , @agnes512  have we tested many levels of inheritance? Or just one level (B extends A)?

**Comment by Salketer** [comment]
@emonddr the cli prompts if the definition is not directly in the file. It does not detect inheritance, it just does not fail anymore as it asks the user for the key information instead of stopping with an error.

For completeness, not only inheritance can fool the CLI trying to determine the key property and type. You could use variables:

`@property(BasicKeyDefinition)` where `BasicKeyDefinition` holds the configuration object for the key shared by all models;

**Review by nabdelgadir — APPROVED** [review]

**Comment by agnes512** [comment]
> Just wondering if someone doesn't use the CLI . What if they look at the docs and construct it by hand, do we have the necessary stuff in the docs to help them. Just curious. thx

@emonddr If I remember correctly we were doing it by hand before we had the CLI. We had instructions and explanations in tutorials and Relation docs. But mostly it was just copy-paste. A community user initialized the relation CLI and we improve it overtime 😄 I think it's way more easier to create relations over the CLI. 
Our current [Relations](https://loopback.io/doc/en/lb4/Relations.html) docs have details of all crucial parts. Users should be able to create/modify relations without the CLI. Hope I answered your question!

**Comment by emonddr** [comment]
> @emonddr the cli prompts if the definition is not directly in the file. It does not detect inheritance, it just does not fail anymore as it asks the user for the key information instead of stopping with an error.
> 
> For completeness, not only inheritance can fool the CLI trying to determine the key property and type. You could use variables:
> 
> `@property(BasicKeyDefinition)` where `BasicKeyDefinition` holds the configuration object for the key shared by all models;

The title of this PR is 'allow model inheritance', so my question is : Are there test cases that handle inheritance that is 1 level deep ( B extends A), and are there other tests to see if deeper inheritance levels are handled (D extends C, C extends B, and B extends A) ?

**Comment by Salketer** [comment]
What I am saying is that before, cli did not allow inheritance at all. It
just exited with an error because it could not detect the key in the model
file. What this PR provides is a fallback with prompts to still allow
creating the relation through cli.

Maybe the title is a little misleading, but it is not "auto detect keys in
prototype chain of models".

For my use cases stated earlier, it does allow me to use the cli for
relations, while before I couldn't. Hope it clears it up!? 😊

**Comment by agnes512** [comment]
> Are there test cases that handle inheritance that is 1 level deep ( B extends A), and are there other tests to see if deeper inheritance levels are handled (D extends C, C extends B, and B extends A) ?

@emonddr  These test cases are meant to check if the new prompts provide correct names and types for models, so that models with relations inherit correctly. The functionality of inheritance itself should be tested in model/repository level, not the CLI. I also updated the title if it makes more sense to you. Thanks.

**Pull request merged**
