### PR TITLE
feat(cli): jundrop2

### PR DESCRIPTION
**Pull request by candytangnb**
gvt jun drop2

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@candytangnb, thanks for the PR. Do you mind to have update the commit message to be more related to the changes? My suggestion would be: `feat(cli): update translation messages`.  Other than that, the PR LGTM. Thanks.

**Comment by candytangnb** [comment]
Sorry that I am sure of how to change the commit message ?

**Comment by agnes512** [comment]
I can help you update the message.

**Comment by dhmlau** [comment]
Thanks @agnes512. 
@candytangnb, your PR has landed 🎉. Thanks!

**Pull request merged**
